### ISSUE TITLE
LLT/JBD BLE - Connection to battery not stable

### ISSUE THREAD

**Issue by dsrawding** [Louisvdw/dbus-serialbattery#1013]
### Describe the bug

The Pi has no problem connecting to the battery and data flows for a few seconds then disconnects.  I have added a second Bluetooth adapter hoping it would help but it does not.  I have tried all available versions.  With debugging on I notice this error:  ERROR: BMS send insufficient data. Received 40 expected 41.  That seems to be when it dies.  The XiaoXiang app runs fine and has no issue staying connected to the battery.
<img width="288" alt="Screenshot 2024-03-20 at 11 30 37 AM" src="https://github.com/Louisvdw/dbus-serialbattery/assets/43624757/e9b18089-151b-4dff-ba0e-ae75a20776ae">
<img width="286" alt="Screenshot 2024-03-20 at 11 30 57 AM" src="https://github.com/Louisvdw/dbus-serialbattery/assets/43624757/c4ff23af-7dd6-4a26-af3c-23dabfb67365">
<img width="644" alt="Screenshot 2024-03-20 at 10 37 59 AM" src="https://github.com/Louisvdw/dbus-serialbattery/assets/43624757/dd66fe39-e343-426d-b8fa-66e6036c6048">

### How to reproduce

Install and run bus-serialbattery.

### Expected behavior

Data would be received from battery more than once

### Driver version

1.2.20240227beta

### Venus OS device type

Raspberry Pi 3

### Venus OS version

v3.30

### BMS type

Smart BMS (LLT, JBD, Overkill Solar)

### Cell count

4

### Battery count

1

### Connection type

Bluetooth

### Config file

```ini
[DEFAULT]

; --------- Set logging level ---------
; ERROR: Only errors are logged
; WARNING: Errors and warnings are logged
; INFO: Errors, warnings and info messages are logged
; DEBUG: Errors, warnings, info and debug messages are logged
LOGGING = WARNING
BLOCK_ON_DISCONNECT = False

; --------- Bluetooth BMS ---------
; Description:
;     Specify the Bluetooth BMS and it's MAC address that you want to install. Leave emty to disable
; Available Bluetooth BMS:
;     Jkbms_Ble, LltJbd_Ble
BLUETOOTH_BMS = LltJbd_Ble A5:C2:37:08:0A:89
```

### Relevant log output

```shell
2024-03-20 15:01:53.285119500 *** CCGX booted (0) ***
tail: /data/log/dbus-blebattery.0/current has been replaced; following end of new file
2024-03-20 15:03:07.576519500 
2024-03-20 15:03:07.576523500 INFO:Bluetooth details
2024-03-20 15:03:07.679883500 Attempting to disconnect from A5:C2:37:08:0A:89
2024-03-20 15:03:07.679892500 Successful disconnected
2024-03-20 15:03:12.960180500 Device A5:C2:37:08:0A:89 (public)
2024-03-20 15:03:12.960187500 	Alias: Lisuateli12V100aH
2024-03-20 15:03:12.960190500 	Paired: no
2024-03-20 15:03:12.960191500 	Trusted: yes
2024-03-20 15:03:12.960193500 	Blocked: no
2024-03-20 15:03:12.960195500 	Connected: no
2024-03-20 15:03:12.960197500 	LegacyPairing: no
2024-03-20 15:03:12.960199500 	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
2024-03-20 15:03:12.960203500 	RSSI: -49
2024-03-20 15:03:12.960205500 
2024-03-20 15:03:17.743457500 INFO:SerialBattery:
2024-03-20 15:03:17.744172500 INFO:SerialBattery:Starting dbus-serialbattery
2024-03-20 15:03:17.745945500 INFO:SerialBattery:Venus OS v3.30
2024-03-20 15:03:17.746410500 INFO:SerialBattery:dbus-serialbattery v1.2.20240227beta
2024-03-20 15:03:34.400251500 Traceback (most recent call last):
2024-03-20 15:03:34.400257500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 257, in <module>
2024-03-20 15:03:34.400262500     main()
2024-03-20 15:03:34.400264500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 187, in main
2024-03-20 15:03:34.400269500     testbms = class_("", 9600, sys.argv[2])
2024-03-20 15:03:34.400272500   File "/opt/victronenergy/dbus-serialbattery/bms/lltjbd_ble.py", line 53, in __init__
2024-03-20 15:03:34.400413500     execfile.write(execpath.group())
2024-03-20 15:03:34.400416500 AttributeError: 'NoneType' object has no attribute 'group'
2024-03-20 15:03:34.702919500 
2024-03-20 15:03:34.703057500 INFO:Bluetooth details
2024-03-20 15:03:34.748684500 [CHG] Device A5:C2:37:08:0A:89 RSSI: -49
2024-03-20 15:03:34.850887500 Attempting to disconnect from A5:C2:37:08:0A:89
2024-03-20 15:03:34.850894500 Successful disconnected
2024-03-20 15:03:39.969540500 Device A5:C2:37:08:0A:89 (public)
2024-03-20 15:03:39.969547500 	Alias: Lisuateli12V100aH
2024-03-20 15:03:39.969549500 	Paired: no
2024-03-20 15:03:39.969551500 	Trusted: yes
2024-03-20 15:03:39.969553500 	Blocked: no
2024-03-20 15:03:39.969555500 	Connected: no
2024-03-20 15:03:39.969556500 	LegacyPairing: no
2024-03-20 15:03:39.969558500 	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
2024-03-20 15:03:39.969563500 	RSSI: -50
2024-03-20 15:03:39.970461500 
2024-03-20 15:03:41.320911500 INFO:SerialBattery:
2024-03-20 15:03:41.321741500 INFO:SerialBattery:Starting dbus-serialbattery
2024-03-20 15:03:41.323504500 INFO:SerialBattery:Venus OS v3.30
2024-03-20 15:03:41.324149500 INFO:SerialBattery:dbus-serialbattery v1.2.20240227beta
2024-03-20 15:03:57.876241500 INFO:SerialBattery:Init of LltJbd_Ble at A5:C2:37:08:0A:89
2024-03-20 15:03:57.876839500 INFO:SerialBattery:Test of LltJbd_Ble at A5:C2:37:08:0A:89
2024-03-20 15:04:03.084668500 DEBUG:SerialBattery:bytearray: \xdd\x05\x00\x0f\x44\x50\x30\x34\x53\x30\x30\x37\x4c\x34\x53\x31\x30\x30\x41\xfc\x6a\x77
2024-03-20 15:04:03.085247500 DEBUG:SerialBattery:DP04S007L4S100A
2024-03-20 15:04:03.386480500 DEBUG:SerialBattery:bytearray: \xdd\x03\x00\x22\x05\x2a\xfe\xf5\x22\xa7\x27\x10\x00\x01\x2f\x86\x00\x00\x00\x00\x00\x00\xd6\x59\x03\x04\x01\x0b\x4f\x00\x00\x00\x27\x10\x22\xa7\x00\x07\xf9\x6e\x77
2024-03-20 15:04:03.683916500 DEBUG:SerialBattery:bytearray: \xdd\x00\x00\x00\x00\x00\x77
2024-03-20 15:04:03.983812500 DEBUG:SerialBattery:bytearray: \xdd\x11\x00\x02\x1f\x40\xff\x9f\x77
2024-03-20 15:04:04.296097500 DEBUG:SerialBattery:bytearray: \xdd\x28\x00\x02\x2a\xf8\xfe\xdc\x77
2024-03-20 15:04:04.587381500 DEBUG:SerialBattery:bytearray: \xdd\x29\x00\x02\xd5\x08\xff\x21\x77
2024-03-20 15:04:04.902843500 DEBUG:SerialBattery:bytearray: \xdd\x2d\x00\x02\x00\x06\xff\xf8\x77
2024-03-20 15:04:05.240614500 DEBUG:SerialBattery:bytearray: \xdd\x03\x00\x22\x05\x2a\xfe\xf5\x22\xa7\x27\x10\x00\x01\x2f\x86\x00\x00\x00\x00\x00\x00\xd6\x59\x03\x04\x01\x0b\x4f\x00\x00\x00\x27\x10\x22\xa7\x00\x07\xf9\x6e
2024-03-20 15:04:05.241170500 ERROR:SerialBattery:>>> ERROR: BMS send insufficient data. Received 40 expected 41
2024-03-20 15:04:05.241680500 ERROR:SerialBattery:No BMS found at A5:C2:37:08:0A:89
2024-03-20 15:04:05.242127500 ERROR:SerialBattery:ERROR >>> No battery connection at LltJbd_Ble
2024-03-20 15:04:05.242389500 #0
2024-03-20 15:04:05.242390500 #1
2024-03-20 15:04:05.242392500 #2
2024-03-20 15:04:05.242393500 #3
2024-03-20 15:04:08.030748500 INFO:SerialBattery:BLE client disconnected
2024-03-20 15:04:08.309991500 
2024-03-20 15:04:08.421251500 Attempting to disconnect from A5:C2:37:08:0A:89
2024-03-20 15:04:08.421496500 Successful disconnected
2024-03-20 15:04:13.531677500 Device A5:C2:37:08:0A:89 (public)
2024-03-20 15:04:13.531683500 	Alias: Lisuateli12V100aH
2024-03-20 15:04:13.531685500 	Paired: no
2024-03-20 15:04:13.531687500 	Trusted: yes
2024-03-20 15:04:13.531688500 	Blocked: no
2024-03-20 15:04:13.531690500 	Connected: no
2024-03-20 15:04:13.531692500 	LegacyPairing: no
2024-03-20 15:04:13.531694500 	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
2024-03-20 15:04:13.531698500 	RSSI: -49
2024-03-20 15:04:13.532903500 
2024-03-20 15:04:14.722046500 INFO:SerialBattery:
2024-03-20 15:04:14.722667500 INFO:SerialBattery:Starting dbus-serialbattery
2024-03-20 15:04:14.724197500 INFO:SerialBattery:Venus OS v3.30
2024-03-20 15:04:14.724756500 INFO:SerialBattery:dbus-serialbattery v1.2.20240227beta
2024-03-20 15:04:31.380807500 INFO:SerialBattery:Init of LltJbd_Ble at A5:C2:37:08:0A:89
2024-03-20 15:04:31.381478500 INFO:SerialBattery:Test of LltJbd_Ble at A5:C2:37:08:0A:89
2024-03-20 15:04:36.587188500 DEBUG:SerialBattery:bytearray: \xdd\x05\x00\x0f\x44\x50\x30\x34\x53\x30\x30\x37\x4c\x34\x53\x31\x30\x30\x41\xfc\x6a\x77
2024-03-20 15:04:36.587865500 DEBUG:SerialBattery:DP04S007L4S100A
2024-03-20 15:04:36.887813500 DEBUG:SerialBattery:bytearray: \xdd\x03\x00\x22\x05\x2a\xfe\xec\x22\xa4\x27\x10\x00\x01\x2f\x86\x00\x00\x00\x00\x00\x00\xd6\x59\x03\x04\x01\x0b\x4f\x00\x00\x00\x27\x10\x22\xa4\x00\x07\xf9\x7d\x77
2024-03-20 15:04:37.184813500 DEBUG:SerialBattery:bytearray: \xdd\x00\x00\x00\x00\x00\x77
2024-03-20 15:04:38.877443500 DEBUG:SerialBattery:bytearray: \xdd\x11\x00\x02\x1f\x40\xff\x9f\x77
2024-03-20 15:04:39.136117500 DEBUG:SerialBattery:bytearray: \xdd\x28\x00\x02\x2a\xf8\xfe\xdc\x77
2024-03-20 15:04:39.434259500 DEBUG:SerialBattery:bytearray: \xdd\x29\x00\x02\xd5\x08\xff\x21\x77
2024-03-20 15:04:39.734616500 DEBUG:SerialBattery:bytearray: \xdd\x2d\x00\x02\x00\x06\xff\xf8\x77
2024-03-20 15:04:40.036605500 DEBUG:SerialBattery:bytearray: \xdd\x03\x00\x22\x05\x2a\xfe\xec\x22\xa4\x27\x10\x00\x01\x2f\x86\x00\x00\x00\x00\x00\x00\xd6\x59\x03\x04\x01\x0b\x4f\x00\x00\x00\x27\x10\x22\xa4\x00\x07\xf9\x7d
2024-03-20 15:04:40.037358500 ERROR:SerialBattery:>>> ERROR: BMS send insufficient data. Received 40 expected 41
2024-03-20 15:04:40.037920500 ERROR:SerialBattery:No BMS found at A5:C2:37:08:0A:89
2024-03-20 15:04:40.038708500 ERROR:SerialBattery:ERROR >>> No battery connection at LltJbd_Ble
2024-03-20 15:04:40.041163500 #0
2024-03-20 15:04:40.041165500 #1
2024-03-20 15:04:40.041167500 #2
2024-03-20 15:04:40.041168500 #3
2024-03-20 15:04:42.036881500 INFO:SerialBattery:BLE client disconnected
2024-03-20 15:04:42.297978500 
2024-03-20 15:04:42.298287500 INFO:Bluetooth details
2024-03-20 15:04:42.324427500 [CHG] Device A5:C2:37:08:0A:89 RSSI: -49
2024-03-20 15:04:42.324434500 [CHG] Device A5:C2:37:08:0A:89 RSSI: -50
2024-03-20 15:04:42.403858500 Attempting to disconnect from A5:C2:37:08:0A:89
2024-03-20 15:04:42.404033500 Successful disconnected
2024-03-20 15:04:47.501176500 Device A5:C2:37:08:0A:89 (public)
2024-03-20 15:04:47.501183500 	Alias: Lisuateli12V100aH
2024-03-20 15:04:47.501185500 	Paired: no
2024-03-20 15:04:47.501187500 	Trusted: yes
2024-03-20 15:04:47.501189500 	Blocked: no
2024-03-20 15:04:47.501190500 	Connected: no
2024-03-20 15:04:47.501192500 	LegacyPairing: no
2024-03-20 15:04:47.501194500 	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
2024-03-20 15:04:47.501199500 	RSSI: -48
2024-03-20 15:04:47.502705500 
2024-03-20 15:04:48.654102500 INFO:SerialBattery:
2024-03-20 15:04:48.654895500 INFO:SerialBattery:Starting dbus-serialbattery
2024-03-20 15:04:48.656612500 INFO:SerialBattery:Venus OS v3.30
2024-03-20 15:04:48.659562500 INFO:SerialBattery:dbus-serialbattery v1.2.20240227beta
2024-03-20 15:05:05.145863500 INFO:SerialBattery:Init of LltJbd_Ble at A5:C2:37:08:0A:89
2024-03-20 15:05:05.146269500 INFO:SerialBattery:Test of LltJbd_Ble at A5:C2:37:08:0A:89
2024-03-20 15:05:10.337510500 DEBUG:SerialBattery:bytearray: \xdd\x05\x00\x0f\x44\x50\x30\x34\x53\x30\x30\x37\x4c\x34\x53\x31\x30\x30\x41\xfc\x6a\x77
2024-03-20 15:05:10.338249500 DEBUG:SerialBattery:DP04S007L4S100A
2024-03-20 15:05:10.636866500 DEBUG:SerialBattery:bytearray: \xdd\x03\x00\x22\x05\x2a\xfe\xec\x22\xa2\x27\x10\x00\x01\x2f\x86\x00\x00\x00\x00\x00\x00\xd6\x59\x03\x04\x01\x0b\x4f\x00\x00\x00\x27\x10\x22\xa2\x00\x07\xf9\x81
2024-03-20 15:05:10.637464500 ERROR:SerialBattery:>>> ERROR: BMS send insufficient data. Received 40 expected 41
2024-03-20 15:05:10.637941500 ERROR:SerialBattery:No BMS found at A5:C2:37:08:0A:89
2024-03-20 15:05:10.638453500 ERROR:SerialBattery:ERROR >>> No battery connection at LltJbd_Ble
2024-03-20 15:05:13.051981500 INFO:SerialBattery:BLE client disconnected
2024-03-20 15:05:13.314601500
```

### Any other information that may be helpful

bluetoothctl
[Lisuateli12V100aH]# info
Device A5:C2:37:08:0A:89 (public)
	Name: Lisuateli12V100aH
	Alias: Lisuateli12V100aH
	Paired: no
	Trusted: yes
	Blocked: no
	Connected: yes
	LegacyPairing: no
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
	UUID: Unknown                   (0000ff00-0000-1000-8000-00805f9b34fb)
	UUID: Vendor specific           (00010203-0405-0607-0809-0a0b0c0d1912)
	Modalias: usb:v248Ap8266d0001
	ManufacturerData Key: 0x0a89
	ManufacturerData Value:
  08 37 c2 a5                                      .7..            
	RSSI: -48
	AdvertisingFlags:
  06                                               .

**Comment by dsrawding** [comment]
I have been trying different versions and trying to get this to work for a few days with no luck.

**Comment by mr-manuel** [comment]
I have no idea on how to fix that. Some help of the community would be appreciated. The Bluetooth connection is also not stable for the JKBMS, maybe we have some design mistake or anything else.

**Comment by dsrawding** [comment]
Can someone point me to what code parses the data from the BMS?  I'm happy to try to figure out what piece of data is missing or modify my local code to only look for 40 rather than 41.

**Comment by Marvo2011** [comment]
> I have added a second Bluetooth adapter hoping it would help but it does not.

Have you tried latest master with `BLUETOOTH_USE_USB = True` in config.ini?
Have your Bluetooth adapter BLE support ? Bluetooth version >4.0

**Comment by Marvo2011** [comment]
@dsrawding Can you post your output from `hciconfig -a`

**Comment by dsrawding** [comment]
I don't believe the issue was with the Bluetooth.  I tested by disabling the internal interface and it didn't make a difference.  I have given up on using Bluetooth and cut the battery case open and connected using the uart port on the BMS and it's working with dubs-serialbattery.  Thanks.

**Comment by doctortuta46** [comment]
I had the same problem, using jbdBMS and Venus OS Raspberry Pi v 3.67.
The solution I used was to increase the pool interval configuration to
`POLL_INTERVAL = 5` in config.ini
So far, the problem has been resolved for my system.
