### ISSUE TITLE
Dbus-serial battery driver no longer recognized

### ISSUE THREAD

**Issue by NorthTown2022** [Louisvdw/dbus-serialbattery#1133]
### Describe the problem

dbus-serial battery driver has stopped working and is no longer seen by the GX under Device list.
![image](https://github.com/user-attachments/assets/1e85b273-5dc1-4111-a2ee-346ea140cca3)

### Driver version

v1.4.20240928

### Venus OS device type

Cerbo GX

### Venus OS version

v3.30

### BMS type

JKBMS / Heltec BMS

### Cell count

16

### Battery count

1

### Connection type

Serial USB adapter to RS485

### Config file

```ini
BMS_TYPE = Jkbms
LOGGING = INFO

MAX_BATTERY_CHARGE_CURRENT = 140
MAX_BATTERY_DISCHARGE_CURRENT = 100

; --------- Cell Voltages ---------
; Description: Cell min/max voltages which are used to calculate the min/max ba                                                                             >
; Example: 16 cells * 3.45V/cell = 55.2V max charge voltage. 16 cells * 2.90V =                                                                             >
MIN_CELL_VOLTAGE   = 2.900
; Max voltage (can seen as absorption voltage)
MAX_CELL_VOLTAGE   = 3.450
; Float voltage (can be seen as resting voltage)
FLOAT_CELL_VOLTAGE = 3.350

; --------- SOC reset voltage ---------
SOC_RESET_VOLTAGE = 3.620

; --------- SOC calculation ---------
SOC_CALCULATION = TRUE
SOC_RESET_CURRENT = 7
SOC_RESET_TIME = 60
SOC_CALC_CURRENT_REPORTED_BY_BMS  = -300, 300
SOC_CALC_CURRENT_MEASURED_BY_USER = -300, 300

; Temperature sensor 1 name
TEMP_1_NAME = Temp Cells 4|5

; Temperature sensor 2 name
TEMP_2_NAME = Temp Cells 12|13

LINEAR_LIMITATION_ENABLE = True

CVCM_ENABLE = True
CCCM_CV_ENABLE = True
DCCM_CV_ENABLE = True
CCCM_T_ENABLE = True
DCCM_T_ENABLE = True

; --------- Cell Voltage limitation (affecting CVL) ---------
CVL_ICONTROLLER_MODE = True
CVL_ICONTROLLER_FACTOR = 0.2
```

### Relevant log output

```shell
root@einstein:~# tail -F -n 100 /data/log/dbus-serialbattery.ttyUSB0/current | tai64nlocal
2024-10-11 22:52:22.317767500   File "/opt/victronenergy/dbus-serialbattery/utils.py", line 44, in <module>
2024-10-11 22:52:22.327047500     config.read([default_config_file_path, custom_config_file_path])
2024-10-11 22:52:22.327056500   File "/usr/lib/python3.8/configparser.py", line 697, in read
2024-10-11 22:52:22.327060500     self._read(fp, filename)
2024-10-11 22:52:22.327062500   File "/usr/lib/python3.8/configparser.py", line 1082, in _read
2024-10-11 22:52:22.327065500     raise MissingSectionHeaderError(fpname, lineno, line)
2024-10-11 22:52:22.327244500 configparser.MissingSectionHeaderError: File contains no section headers.
2024-10-11 22:52:22.327249500 file: '/opt/victronenergy/dbus-serialbattery/config.ini', line: 1
2024-10-11 22:52:22.327252500 'BMS_TYPE = Jkbms\n'
2024-10-11 22:52:58.015947500 Traceback (most recent call last):
2024-10-11 22:52:58.015957500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 16, in <module>
2024-10-11 22:52:58.015960500     from dbushelper import DbusHelper
2024-10-11 22:52:58.015963500   File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 8, in <module>
2024-10-11 22:52:58.015966500     from utils import logger, publish_config_variables
2024-10-11 22:52:58.015969500   File "/opt/victronenergy/dbus-serialbattery/utils.py", line 44, in <module>
2024-10-11 22:52:58.016159500     config.read([default_config_file_path, custom_config_file_path])
2024-10-11 22:52:58.016164500   File "/usr/lib/python3.8/configparser.py", line 697, in read
2024-10-11 22:52:58.016167500     self._read(fp, filename)
2024-10-11 22:52:58.016169500   File "/usr/lib/python3.8/configparser.py", line 1082, in _read
2024-10-11 22:52:58.016172500     raise MissingSectionHeaderError(fpname, lineno, line)
2024-10-11 22:52:58.016213500 configparser.MissingSectionHeaderError: File contains no section headers.
2024-10-11 22:52:58.016216500 file: '/opt/victronenergy/dbus-serialbattery/config.ini', line: 1
2024-10-11 22:52:58.016219500 'BMS_TYPE = Jkbms\n'
2024-10-11 22:53:36.537783500 Traceback (most recent call last):
2024-10-11 22:53:36.537792500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 16, in <module>
2024-10-11 22:53:36.537796500     from dbushelper import DbusHelper
2024-10-11 22:53:36.537798500   File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 8, in <module>
2024-10-11 22:53:36.537802500     from utils import logger, publish_config_variables
2024-10-11 22:53:36.537804500   File "/opt/victronenergy/dbus-serialbattery/utils.py", line 44, in <module>
2024-10-11 22:53:36.537963500     config.read([default_config_file_path, custom_config_file_path])
2024-10-11 22:53:36.537966500   File "/usr/lib/python3.8/configparser.py", line 697, in read
2024-10-11 22:53:36.537970500     self._read(fp, filename)
2024-10-11 22:53:36.537971500   File "/usr/lib/python3.8/configparser.py", line 1082, in _read
2024-10-11 22:53:36.537974500     raise MissingSectionHeaderError(fpname, lineno, line)
2024-10-11 22:53:36.538003500 configparser.MissingSectionHeaderError: File contains no section headers.
2024-10-11 22:53:36.538007500 file: '/opt/victronenergy/dbus-serialbattery/config.ini', line: 1
2024-10-11 22:53:36.538010500 'BMS_TYPE = Jkbms\n'
2024-10-11 22:54:13.576974500 Traceback (most recent call last):
2024-10-11 22:54:13.576983500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 16, in <module>
2024-10-11 22:54:13.576986500     from dbushelper import DbusHelper
2024-10-11 22:54:13.576989500   File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 8, in <module>
2024-10-11 22:54:13.576992500     from utils import logger, publish_config_variables
2024-10-11 22:54:13.576995500   File "/opt/victronenergy/dbus-serialbattery/utils.py", line 44, in <module>
2024-10-11 22:54:13.577149500     config.read([default_config_file_path, custom_config_file_path])
2024-10-11 22:54:13.577153500   File "/usr/lib/python3.8/configparser.py", line 697, in read
2024-10-11 22:54:13.577156500     self._read(fp, filename)
2024-10-11 22:54:13.577158500   File "/usr/lib/python3.8/configparser.py", line 1082, in _read
2024-10-11 22:54:13.577161500     raise MissingSectionHeaderError(fpname, lineno, line)
2024-10-11 22:54:13.577193500 configparser.MissingSectionHeaderError: File contains no section headers.
2024-10-11 22:54:13.577196500 file: '/opt/victronenergy/dbus-serialbattery/config.ini', line: 1
2024-10-11 22:54:13.577199500 'BMS_TYPE = Jkbms\n'
^C
root@einstein:~# tail -F -n 100 /data/log/serial-starter/current | grep dbus-serialbattery | tai64nlocal
^C
root@einstein:~# tail -F /data/log/serial-starter/current | tai64nlocal
2024-10-11 22:58:03.127628500 INFO: Start service dbus-modbus-client.serial.ttyUSB0 once
2024-10-11 22:58:10.961858500 INFO: Start service dbus-serialbattery.ttyUSB0 once
2024-10-11 22:58:14.222418500 INFO: Start service gps-dbus.ttyUSB0 once
2024-10-11 22:58:23.698973500 INFO: Start service vedirect-interface.ttyUSB0 once
2024-10-11 22:58:29.099725500 INFO: Start service dbus-cgwacs.ttyUSB0 once
2024-10-11 22:58:34.475991500 INFO: Start service dbus-fzsonick-48tl.ttyUSB0 once
2024-10-11 22:58:39.838659500 INFO: Start service dbus-imt-si-rs485tc.ttyUSB0 once
2024-10-11 22:58:43.197819500 INFO: Start service dbus-modbus-client.serial.ttyUSB0 once
2024-10-11 22:58:51.019007500 INFO: Start service dbus-serialbattery.ttyUSB0 once
2024-10-11 22:58:54.340318500 INFO: Start service gps-dbus.ttyUSB0 once
2024-10-11 22:59:03.729310500 INFO: Start service vedirect-interface.ttyUSB0 once
^C
root@einstein:~# tail -F /data/log/serial-starter/current | tai64nlocal
2024-10-11 22:58:34.475991500 INFO: Start service dbus-fzsonick-48tl.ttyUSB0 once
2024-10-11 22:58:39.838659500 INFO: Start service dbus-imt-si-rs485tc.ttyUSB0 once
2024-10-11 22:58:43.197819500 INFO: Start service dbus-modbus-client.serial.ttyUSB0 once
2024-10-11 22:58:51.019007500 INFO: Start service dbus-serialbattery.ttyUSB0 once
2024-10-11 22:58:54.340318500 INFO: Start service gps-dbus.ttyUSB0 once
2024-10-11 22:59:03.729310500 INFO: Start service vedirect-interface.ttyUSB0 once
2024-10-11 22:59:09.085770500 INFO: Start service dbus-cgwacs.ttyUSB0 once
2024-10-11 22:59:14.429160500 INFO: Start service dbus-fzsonick-48tl.ttyUSB0 once
2024-10-11 22:59:19.808347500 INFO: Start service dbus-imt-si-rs485tc.ttyUSB0 once
2024-10-11 22:59:25.173176500 INFO: Start service dbus-modbus-client.serial.ttyUSB0 once
2024-10-11 22:59:32.653279500 INFO: Start service dbus-serialbattery.ttyUSB0 once
2024-10-11 22:59:36.043245500 INFO: Start service gps-dbus.ttyUSB0 once
2024-10-11 22:59:43.387008500 INFO: Start service vedirect-interface.ttyUSB0 once
^C
root@einstein:~# ls -l /dev/ttyUSB*
ls: /dev/ttyUSB*: No such file or directory
root@einstein:~# ls -l /dev/ttyUSB0
ls: /dev/ttyUSB0: No such file or directory
root@einstein:~# ls -l /dev/ttyUSB*
ls: /dev/ttyUSB*: No such file or directory
root@einstein:~# ls -l /dev/ttyUSB*
crw-rw----    1 root     dialout   188,   0 Oct 11 23:01 /dev/ttyUSB0
root@einstein:~# ls -l /dev/ttyUSB*
crw-rw----    1 root     dialout   188,   0 Oct 11 23:01 /dev/ttyUSB0
root@einstein:~# ls -l /dev/ttyUSB0
crw-rw----    1 root     dialout   188,   0 Oct 11 23:01 /dev/ttyUSB0
root@einstein:~# rter/*
-sh: rter/*: No such file or directory
root@einstein:~# rter/*
-sh: rter/*: No such file or directory
root@einstein:~# head /data/var/lib/serial-starter/*
==> /data/var/lib/serial-starter/ttyS4 <==
mkx

==> /data/var/lib/serial-starter/ttyS5 <==
vedirect

==> /data/var/lib/serial-starter/ttyS6 <==
vedirect

==> /data/var/lib/serial-starter/ttyS7 <==
vedirect

==> /data/var/lib/serial-starter/ttyUSB0 <==
imt
root@einstein:~# tail -F /data/log/dbus-serialbattery.ttyUSB0/current | tai64nlocal
2024-10-11 23:02:47.876498500     from utils import logger, publish_config_variables
2024-10-11 23:02:47.876501500   File "/opt/victronenergy/dbus-serialbattery/utils.py", line 44, in <module>
2024-10-11 23:02:47.876669500     config.read([default_config_file_path, custom_config_file_path])
2024-10-11 23:02:47.876673500   File "/usr/lib/python3.8/configparser.py", line 697, in read
2024-10-11 23:02:47.876676500     self._read(fp, filename)
2024-10-11 23:02:47.876678500   File "/usr/lib/python3.8/configparser.py", line 1082, in _read
2024-10-11 23:02:47.876681500     raise MissingSectionHeaderError(fpname, lineno, line)
2024-10-11 23:02:47.876714500 configparser.MissingSectionHeaderError: File contains no section headers.
2024-10-11 23:02:47.876719500 file: '/opt/victronenergy/dbus-serialbattery/config.ini', line: 1
2024-10-11 23:02:47.876722500 'BMS_TYPE = Jkbms\n'
2024-10-11 23:03:27.782967500 Traceback (most recent call last):
2024-10-11 23:03:27.782975500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 16, in <module>
2024-10-11 23:03:27.782979500     from dbushelper import DbusHelper
2024-10-11 23:03:27.782982500   File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 8, in <module>
2024-10-11 23:03:27.782985500     from utils import logger, publish_config_variables
2024-10-11 23:03:27.782988500   File "/opt/victronenergy/dbus-serialbattery/utils.py", line 44, in <module>
2024-10-11 23:03:27.783191500     config.read([default_config_file_path, custom_config_file_path])
2024-10-11 23:03:27.783195500   File "/usr/lib/python3.8/configparser.py", line 697, in read
2024-10-11 23:03:27.783198500     self._read(fp, filename)
2024-10-11 23:03:27.783200500   File "/usr/lib/python3.8/configparser.py", line 1082, in _read
2024-10-11 23:03:27.783203500     raise MissingSectionHeaderError(fpname, lineno, line)
2024-10-11 23:03:27.783237500 configparser.MissingSectionHeaderError: File contains no section headers.
2024-10-11 23:03:27.783240500 file: '/opt/victronenergy/dbus-serialbattery/config.ini', line: 1
2024-10-11 23:03:27.783243500 'BMS_TYPE = Jkbms\n'
2024-10-11 23:04:07.814195500 Traceback (most recent call last):
2024-10-11 23:04:07.814205500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 16, in <module>
2024-10-11 23:04:07.814209500     from dbushelper import DbusHelper
2024-10-11 23:04:07.814211500   File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 8, in <module>
2024-10-11 23:04:07.814214500     from utils import logger, publish_config_variables
2024-10-11 23:04:07.814217500   File "/opt/victronenergy/dbus-serialbattery/utils.py", line 44, in <module>
2024-10-11 23:04:07.814402500     config.read([default_config_file_path, custom_config_file_path])
2024-10-11 23:04:07.814407500   File "/usr/lib/python3.8/configparser.py", line 697, in read
2024-10-11 23:04:07.814410500     self._read(fp, filename)
2024-10-11 23:04:07.814412500   File "/usr/lib/python3.8/configparser.py", line 1082, in _read
2024-10-11 23:04:07.814415500     raise MissingSectionHeaderError(fpname, lineno, line)
2024-10-11 23:04:07.814533500 configparser.MissingSectionHeaderError: File contains no section headers.
2024-10-11 23:04:07.814538500 file: '/opt/victronenergy/dbus-serialbattery/config.ini', line: 1
2024-10-11 23:04:07.814541500 'BMS_TYPE = Jkbms\n'
^C
root@einstein:~# svstat /service/dbus-serialbattery.tty*
/service/dbus-serialbattery.ttyUSB0: down 8 seconds, normally up
root@einstein:~#
```

### Any other information that may be helpful

The driver was installed and working perfectly for many months alongside GUI mods on Venus OS 3.30 Large (I am using a flow to control Grafana on raspberry PI).

I was using an older version of the driver (v1.2.202404xx) and started having some issue where CVL was limited to float voltage well before 100% SOC. I tried to update remotely via Tailscale to v1.4.20240928 and was somewhat successful. The new drive showed up under Device list and Remote Console. After several remote reboots I lost connection to the driver.

I am now at the location and tried to reflash the driver, as well follow all troubleshooting. It seems like there is a problem with the software on the Cerbo GX that does not allow data from the USB port. I tried swapping USB ports but no luck.

I have a spare Cerbo GX that has the driver flashed and it recognized SerialBattery in Device list right away so I can definitely rule out any cabling issues.

**Comment by mr-manuel** [comment]
> `configparser.MissingSectionHeaderError: File contains no section headers.`

Somehow you deleted the first line of your `config.ini`. Add it again and it should work:

https://github.com/Louisvdw/dbus-serialbattery/blob/fd0fc1a193427df6ca0fadd141aa57826f761819/etc/dbus-serialbattery/config.default.ini#L1

**Comment by NorthTown2022** [comment]
Yeah, something happened and my complete config file was empty so I copy and pasted my config from a backup file. Must have missed that first line. Everything works now. Thank you 😀
