### ISSUE TITLE
ERROR Exception during bluetooth installation (jkbms)

### ISSUE THREAD

**Issue by MisterX1000** [Louisvdw/dbus-serialbattery#894]
### Describe the problem

Hi,

I try to connect my jkbms via bluetooth to my Multiplus 2-GX because the cable connection sometimes "lost" my jkbms.

The installation log showed me some errors. All log files are attached. 

I also tried to install "opkg update" "opkg install python3-misc" & "python3-pip" by hand - same error message.

Not sure if the beta firmware (v3.20~34) of my MP2-GX causes this problems. 

It would be very kind of you if you could have a look and help me here.

Thank you very much in advance
Alex

### Driver version

v1.0.20231128beta

### Venus OS device type

GX Card (integrated in Victron device)

### Venus OS version

v3.20~34

### BMS type

JKBMS / Heltec BMS

### Cell count

16

### Connection type

Bluetooth

### Config file

```ini
[DEFAULT]

; If you want to add custom values/settings, then check the values/settings you want to change in "config.default.ini"
; and insert them below to persist future driver updates.

; Example (remove the semicolon ";" to uncomment and activate the value/setting):
; MAX_BATTERY_CHARGE_CURRENT = 50.0
; MAX_BATTERY_DISCHARGE_CURRENT = 60.0


; --------- Bluetooth BMS ---------
; Description: Specify the Bluetooth BMS and it's MAC address that you want to install. Leave emty to disable
; -- Available Bluetooth BMS:
; Jkbms_Ble, LltJbd_Ble
; Example for one BMS:
; BLUETOOTH_BMS = Jkbms_Ble C8:47:8C:00:00:00
; Example for multiple BMS:
; BLUETOOTH_BMS = Jkbms_Ble C8:47:8C:00:00:00, Jkbms_Ble C8:47:8C:00:00:11, Jkbms_Ble C8:47:8C:00:00:22

BLUETOOTH_BMS = Jkbms_Ble C8:47:8C:E5:1C:EB


; --------- SOC limitation (affecting CCL/DCL) ---------
CCCM_SOC_ENABLE = False
DCCM_SOC_ENABLE = False

; --------- Cell Voltages ---------
; Description: Cell min/max voltages which are used to calculate the min/max battery voltage
; Example: 16 cells * 3.45V/cell = 55.2V max charge voltage. 16 cells * 2.90V = 46.4V min discharge voltage
MIN_CELL_VOLTAGE   = 2.70
; Max voltage (can seen as absorption voltage)
MAX_CELL_VOLTAGE   = 3.450
; Float voltage (can be seen as resting voltage)
FLOAT_CELL_VOLTAGE = 3.375

; SOC reset voltage (may be needed to reset the SoC to 100% once in a while for some BMS)
; Has to be higher as the MAX_CELL_VOLTAGE
SOC_RESET_VOLTAGE  = 3.480
SOC_RESET_AFTER_DAYS = 30


; Set steps to reduce battery current
; The current will be changed linear between those steps if LINEAR_LIMITATION_ENABLE is set to True
CELL_VOLTAGES_WHILE_CHARGING   = 3.55, 3.50, 3.45, 3.30
MAX_CHARGE_CURRENT_CV_FRACTION =    0, 0.05,  0.8,    1

CELL_VOLTAGES_WHILE_DISCHARGING   = 2.70, 2.80, 2.90, 3.00
MAX_DISCHARGE_CURRENT_CV_FRACTION =    0,  0.1,  0.3,  0.5
```

### Relevant log output

```shell
root@nanopi:~# tail -F -n 100 /data/log/dbus-blebattery.*/current | tai64nlocal
2023-12-18 21:22:42.581811500 Attempting to disconnect from C8:47:8C:E5:1C:EB
2023-12-18 21:22:42.581822500 [CHG] Device 76:99:13:5E:42:61 TxPower is nil
2023-12-18 21:22:42.581825500 [CHG] Device 76:99:13:5E:42:61 RSSI is nil
2023-12-18 21:22:42.581828500 [CHG] Device 84:69:93:A8:94:4F RSSI is nil
2023-12-18 21:22:42.581830500 [CHG] Device 55:1E:73:09:E5:08 TxPower is nil
2023-12-18 21:22:42.581833500 [CHG] Device 55:1E:73:09:E5:08 RSSI is nil
2023-12-18 21:22:42.581835500 [CHG] Device 64:11:DD:FC:8C:6C TxPower is nil
2023-12-18 21:22:42.582207500 [CHG] Device 64:11:DD:FC:8C:6C RSSI is nil
2023-12-18 21:22:42.582213500 [CHG] Device 42:21:0B:4E:DC:24 RSSI is nil
2023-12-18 21:22:42.582215500 [CHG] Device F0:38:1C:BF:DA:DC TxPower is nil
2023-12-18 21:22:42.582218500 [CHG] Device F0:38:1C:BF:DA:DC RSSI is nil
2023-12-18 21:22:42.582221500 [CHG] Device 57:8D:66:F1:A8:CA RSSI is nil
2023-12-18 21:22:42.582224500 [CHG] Device 6D:F0:4A:12:7C:D7 TxPower is nil
2023-12-18 21:22:42.582262500 [CHG] Device 6D:F0:4A:12:7C:D7 RSSI is nil
2023-12-18 21:22:42.582266500 [CHG] Device 66:8B:AF:A1:0B:07 TxPower is nil
2023-12-18 21:22:42.582269500 [CHG] Device 66:8B:AF:A1:0B:07 RSSI is nil
2023-12-18 21:22:42.582271500 [CHG] Device 78:A0:09:6F:FE:1C TxPower is nil
2023-12-18 21:22:42.582274500 [CHG] Device 78:A0:09:6F:FE:1C RSSI is nil
2023-12-18 21:22:42.582325500 [CHG] Device 64:DE:F7:B2:5C:90 TxPower is nil
2023-12-18 21:22:42.582329500 [CHG] Device 64:DE:F7:B2:5C:90 RSSI is nil
2023-12-18 21:22:42.582331500 [CHG] Device C8:47:8C:E5:1C:EB RSSI is nil
2023-12-18 21:22:42.582334500 [CHG] Device BE:89:B0:03:50:8C RSSI is nil
2023-12-18 21:22:42.582336500 [CHG] Controller 20:57:9E:2C:59:45 Discovering: no
2023-12-18 21:22:42.582359500 Successful disconnected
2023-12-18 21:22:47.661988500 Device C8:47:8C:E5:1C:EB (public)
2023-12-18 21:22:47.661998500   Alias: JK-B2A24S15P
2023-12-18 21:22:47.662000500   Paired: no
2023-12-18 21:22:47.662002500   Trusted: yes
2023-12-18 21:22:47.662004500   Blocked: no
2023-12-18 21:22:47.662005500   Connected: no
2023-12-18 21:22:47.662006500   LegacyPairing: no
2023-12-18 21:22:47.662008500   UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
2023-12-18 21:22:47.662010500   RSSI: -60
2023-12-18 21:22:47.662784500
2023-12-18 21:22:48.767141500 INFO:SerialBattery:
2023-12-18 21:22:48.767651500 INFO:SerialBattery:Starting dbus-serialbattery
2023-12-18 21:22:48.768606500 INFO:SerialBattery:dbus-serialbattery v1.0.20231128beta
2023-12-18 21:22:48.781471500 Traceback (most recent call last):
2023-12-18 21:22:48.781480500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 238, in <module>
2023-12-18 21:22:48.781484500     main()
2023-12-18 21:22:48.781486500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 166, in main
2023-12-18 21:22:48.781490500     from bms.jkbms_ble import Jkbms_Ble  # noqa: F401
2023-12-18 21:22:48.781493500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_ble.py", line 7, in <module>
2023-12-18 21:22:48.781613500     from bms.jkbms_brn import Jkbms_Brn
2023-12-18 21:22:48.781616500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_brn.py", line 2, in <module>
2023-12-18 21:22:48.781620500     from bleak import BleakScanner, BleakClient
2023-12-18 21:22:48.781623500 ModuleNotFoundError: No module named 'bleak'
2023-12-18 21:22:48.957291500
2023-12-18 21:22:48.957475500 INFO:Bluetooth details
2023-12-18 21:22:48.977868500 [CHG] Device C8:47:8C:E5:1C:EB RSSI: -72
2023-12-18 21:22:48.977878500 [CHG] Device C8:47:8C:E5:1C:EB RSSI: -60
2023-12-18 21:22:49.031553500 Attempting to disconnect from C8:47:8C:E5:1C:EB
2023-12-18 21:22:49.031563500 [CHG] Device 57:8D:66:F1:A8:CA RSSI is nil
2023-12-18 21:22:49.031566500 [CHG] Device 51:C6:69:9C:C6:06 TxPower is nil
2023-12-18 21:22:49.031569500 [CHG] Device 51:C6:69:9C:C6:06 RSSI is nil
2023-12-18 21:22:49.031572500 [CHG] Device C3:37:34:32:2E:68 RSSI is nil
2023-12-18 21:22:49.031574500 [CHG] Device 42:21:0B:4E:DC:24 RSSI is nil
2023-12-18 21:22:49.031577500 [CHG] Device 6B:F5:22:A3:0F:38 TxPower is nil
2023-12-18 21:22:49.031811500 [CHG] Device 6B:F5:22:A3:0F:38 RSSI is nil
2023-12-18 21:22:49.031815500 [CHG] Device 64:11:DD:FC:8C:6C TxPower is nil
2023-12-18 21:22:49.031818500 [CHG] Device 64:11:DD:FC:8C:6C RSSI is nil
2023-12-18 21:22:49.031821500 [CHG] Device 76:99:13:5E:42:61 TxPower is nil
2023-12-18 21:22:49.031824500 [CHG] Device 76:99:13:5E:42:61 RSSI is nil
2023-12-18 21:22:49.031850500 [CHG] Device 78:A0:09:6F:FE:1C TxPower is nil
2023-12-18 21:22:49.031853500 [CHG] Device 78:A0:09:6F:FE:1C RSSI is nil
2023-12-18 21:22:49.031855500 [CHG] Device 64:DE:F7:B2:5C:90 TxPower is nil
2023-12-18 21:22:49.031858500 [CHG] Device 64:DE:F7:B2:5C:90 RSSI is nil
2023-12-18 21:22:49.031861500 [CHG] Device 66:8B:AF:A1:0B:07 TxPower is nil
2023-12-18 21:22:49.031863500 [CHG] Device 66:8B:AF:A1:0B:07 RSSI is nil
2023-12-18 21:22:49.031903500 [CHG] Device BE:89:B0:03:50:8C RSSI is nil
2023-12-18 21:22:49.031907500 [CHG] Device F0:38:1C:BF:DA:DC RSSI is nil
2023-12-18 21:22:49.031909500 [CHG] Device 6D:F0:4A:12:7C:D7 TxPower is nil
2023-12-18 21:22:49.031912500 [CHG] Device 6D:F0:4A:12:7C:D7 RSSI is nil
2023-12-18 21:22:49.031914500 [CHG] Device C8:47:8C:E5:1C:EB RSSI is nil
2023-12-18 21:22:49.031917500 [CHG] Controller 20:57:9E:2C:59:45 Discovering: no
2023-12-18 21:22:49.031939500 Successful disconnected
2023-12-18 21:22:54.105671500 Device C8:47:8C:E5:1C:EB (public)
2023-12-18 21:22:54.105684500   Alias: JK-B2A24S15P
2023-12-18 21:22:54.105686500   Paired: no
2023-12-18 21:22:54.105688500   Trusted: yes
2023-12-18 21:22:54.105689500   Blocked: no
2023-12-18 21:22:54.105691500   Connected: no
2023-12-18 21:22:54.105692500   LegacyPairing: no
2023-12-18 21:22:54.105693500   UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
2023-12-18 21:22:54.105696500   RSSI: -70
2023-12-18 21:22:54.106464500
2023-12-18 21:22:55.200506500 INFO:SerialBattery:
2023-12-18 21:22:55.201048500 INFO:SerialBattery:Starting dbus-serialbattery
2023-12-18 21:22:55.202327500 INFO:SerialBattery:dbus-serialbattery v1.0.20231128beta
2023-12-18 21:22:55.216042500 Traceback (most recent call last):
2023-12-18 21:22:55.216056500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 238, in <module>
2023-12-18 21:22:55.216061500     main()
2023-12-18 21:22:55.216062500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 166, in main
2023-12-18 21:22:55.216065500     from bms.jkbms_ble import Jkbms_Ble  # noqa: F401
2023-12-18 21:22:55.216068500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_ble.py", line 7, in <module>
2023-12-18 21:22:55.216218500     from bms.jkbms_brn import Jkbms_Brn
2023-12-18 21:22:55.216221500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_brn.py", line 2, in <module>
2023-12-18 21:22:55.216224500     from bleak import BleakScanner, BleakClient
2023-12-18 21:22:55.216227500 ModuleNotFoundError: No module named 'bleak'
2023-12-18 21:22:55.400004500
2023-12-18 21:22:55.400167500 INFO:Bluetooth details
```

### Any other information that may be helpful

```bash
**root@nanopi:~# python -m pip --version**
pip 20.0.2 from /usr/lib/python3.8/site-packages/pip (python 3.8)
root@nanopi: # cat /opt/victronenergy/version **3v3.20~34**
Victron Energy
20231215181003


**root@nanopi:~# /data/etc/dbus-serialbattery/reinstall-local.sh**

Found 1 Bluetooth BMS in the config file!

Stopping bluetooth: bluetoothd.

Installing required packages to use Bluetooth connection...
Downloading https://updates.victronenergy.com/feeds/venus/release/packages/dunfell/all/Packages.gz.
Updated source 'all'.
Downloading https://updates.victronenergy.com/feeds/venus/release/packages/dunfell/cortexa7hf-neon-vfpv4/Packages.gz.
Updated source 'cortexa7hf-neon-vfpv4'.
Downloading https://updates.victronenergy.com/feeds/venus/release/packages/dunfell/nanopi/Packages.gz.
Updated source 'nanopi'.
No packages installed or removed.

Collecting bleak
  Using cached bleak-0.21.1-py3-none-any.whl (137 kB)
Collecting async-timeout<5,>=3.0.0; python_version < "3.11"
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting typing-extensions>=4.7.0; python_version < "3.12"
  Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting dbus-fast<3,>=1.83.0; platform_system == "Linux"
  Using cached dbus_fast-2.21.0.tar.gz (69 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  
**ERROR: Exception:**
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 515, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/usr/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 151, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/volatile/tmp/pip-build-env-fjkdxfya/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 12, in <module>
    from poetry.core.factory import Factory
  File "/var/volatile/tmp/pip-build-env-fjkdxfya/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 15, in <module>
    from poetry.core.utils.helpers import combine_unicode
  File "/var/volatile/tmp/pip-build-env-fjkdxfya/overlay/lib/python3.8/site-packages/poetry/core/utils/helpers.py", line 19, in <module>
    from poetry.core.version.pep440 import PEP440Version
  File "/var/volatile/tmp/pip-build-env-fjkdxfya/overlay/lib/python3.8/site-packages/poetry/core/version/pep440/__init__.py", line 3, in <module>
    from poetry.core.version.pep440.segments import LocalSegmentType
  File "/var/volatile/tmp/pip-build-env-fjkdxfya/overlay/lib/python3.8/site-packages/poetry/core/version/pep440/segments.py", line 3, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'

done.

Starting bluetooth: bluetoothd.

Installing "Jkbms_Ble" with MAC address "C8:47:8C:E5:1C:EB" as dbus-blebattery.0


No CAN port configuration found in "/data/etc/dbus-serialbattery/config.ini".
You can ignore this, if you are using only a serial connection.



#################
# Install notes #
#################

SERIAL battery connection: The installation is complete. You don't have to do anything more.

BLUETOOTH battery connection: There are a few more steps to complete installation.

    1. Add your Bluetooth BMS to the config file "/data/etc/dbus-serialbattery/config.ini".
       Check the default config file "/data/etc/dbus-serialbattery/config.default.ini" for more informations.
       If your Bluetooth BMS are nearby you can show the MAC address with "bluetoothctl devices".

    2. Make sure to disable Bluetooth in "Settings -> Bluetooth" in the remote console/GUI to prevent reconnects every minute.

    3. Re-run "/data/etc/dbus-serialbattery/reinstall-local.sh", if the Bluetooth BMS were not added to the "config.ini" before.

    ATTENTION!
    If you changed the default connection PIN of your BMS, then you have to pair the BMS first using OS tools like the "bluetoothctl".
    See https://wiki.debian.org/BluetoothUser#Using_bluetoothctl for more details.

CAN battery connection: There are a few more steps to complete installation.

    1. Add your CAN port to the config file "/data/etc/dbus-serialbattery/config.ini".
       Check the default config file "/data/etc/dbus-serialbattery/config.default.ini" for more informations.

    2. Make sure to select a profile with 250 kbit/s in "Settings -> Services -> VE.Can port -> CAN-bus profile" in the remote console/GUI.

    3. Re-run "/data/etc/dbus-serialbattery/reinstall-local.sh", if the CAN port was not added to the "config.ini" before.

CUSTOM SETTINGS: If you want to add custom settings, then check the settings you want to change in "/data/etc/dbus-serialbattery/config.default.ini"
                 and add them to "/data/etc/dbus-serialbattery/config.ini" to persist future driver updates.
```

**Comment by mr-manuel** [comment]
See https://github.com/Louisvdw/dbus-serialbattery/issues?q=No+module+named+%27bleak%27

**Comment by MisterX1000** [comment]
> See https://github.com/Louisvdw/dbus-serialbattery/issues?q=No+module+named+%27bleak%27

Than you very much for your help Manuel,

I tried to install bleak separately, with this commands:

**opkg update
opkg install python3-misc python3-pip
pip3 install bleak**

Or do you mean something else? Or did I miss something?

Thank you very much for your support!
Best regards

Alex

**Comment by mr-manuel** [comment]
You could try to install an older version of bleak like this:

https://github.com/Louisvdw/dbus-serialbattery/issues/819#issuecomment-1791392653

**Comment by MisterX1000** [comment]
Hey Manuel,

unfortunately I got the same error. Log is below. 

Best regards
Alex



root@nanopi:~# **pip3 install dbus-fast==v1.93.0**
Collecting dbus-fast==v1.93.0
  Downloading dbus_fast-1.93.0.tar.gz (67 kB)
     |████████████████████████████████| 67 kB 1.5 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 515, in prepare_linked_requiremen                                                                                               t
    abstract_dist = _get_prepared_distribution(
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_meta                                                                                               data
    self._setup_isolation(finder)
  File "/usr/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 151, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/volatile/tmp/pip-build-env-zncmbttt/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", lin                                                                                               e 12, in <module>
    from poetry.core.factory import Factory
  File "/var/volatile/tmp/pip-build-env-zncmbttt/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 15                                                                                               , in <module>
    from poetry.core.utils.helpers import combine_unicode
  File "/var/volatile/tmp/pip-build-env-zncmbttt/overlay/lib/python3.8/site-packages/poetry/core/utils/helpers.py", l                                                                                               ine 19, in <module>
    from poetry.core.version.pep440 import PEP440Version
  File "/var/volatile/tmp/pip-build-env-zncmbttt/overlay/lib/python3.8/site-packages/poetry/core/version/pep440/__ini                                                                                               t__.py", line 3, in <module>
    from poetry.core.version.pep440.segments import LocalSegmentType
  File "/var/volatile/tmp/pip-build-env-zncmbttt/overlay/lib/python3.8/site-packages/poetry/core/version/pep440/segme                                                                                               nts.py", line 3, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'

root@nanopi:~#

**Comment by MisterX1000** [comment]
Now somethig has changeg, it is not better but now I get the following response from my GX:

**root@nanopi:~# pip3 install bleak**
Traceback (most recent call last):
  File "/usr/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/usr/lib/python3.8/site-packages/pip/_internal/build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 8, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
root@nanopi:~# ^C


**root@nanopi:~# pip3 install dbus-fast==v1.93.0**
Traceback (most recent call last):
  File "/usr/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/usr/lib/python3.8/site-packages/pip/_internal/build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 8, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

**Comment by mr-manuel** [comment]
Seems that something is broken in your installation. Is this a fresh install?

This should fix this error, but probably a new one arises after.

`pip3 install dataclasses`

**Comment by MisterX1000** [comment]
Hey Manuel,

you are right, I also got an error message when I try to install the "dataclasses"

I absolute agree with you, seems to be a problem with the installation. The system is a Victron MP2-GX.

If there is a way to do a complete new installation I don´t know it. I only now how to update the Venus OS and the VE.bus firmware.

<img width="521" alt="image" src="https://github.com/Louisvdw/dbus-serialbattery/assets/112106667/455b636c-b473-42cf-9317-850145e33ac4">

**Comment by mr-manuel** [comment]
Google is your friend: [18. Reset to factory defaults procedure](https://www.victronenergy.com/media/pg/Cerbo-S_GX/en/reset-to-factory-defaults-procedure.html)

**Comment by MisterX1000** [comment]
> Google is your friend: [18. Reset to factory defaults procedure](https://www.victronenergy.com/media/pg/Cerbo-S_GX/en/reset-to-factory-defaults-procedure.html)

I agree ;-) but I don´t have a Cerbo.

But I will figure out how to bring my MP2-GX back to factory defaults - Then I try the serialbattery BT connection with the official Venus OS.

Thanks

**Comment by mr-manuel** [comment]
This is the same for all GX devices.
