### ISSUE TITLE
Multiplus GX crashes while Bluetooth Installation

### ISSUE THREAD

**Issue by arndtw69** [Louisvdw/dbus-serialbattery#934]
### Describe the problem

Because i have issues with interuptions via cable while loading with hight current, i wanted to give bluetooth a try.

I added my JK BMS bluetooth mac to the config. 
then i ran the script
/data/etc/dbus-serialbattery/reinstall-local.sh

Suddenly the Multiplus reboots

When it is restarted i see that it is trying to finish the installation, which hangs again after some time

/var/log/boot shows

`Found 1 Bluetooth BMS in the config file!
Mon Jan 22 17:27:18 2024:
Mon Jan 22 17:27:18 2024: Installing required packages...
Mon Jan 22 17:27:21 2024: Downloading https://updates.victronenergy.com/feeds/venus/release/packages/dunfell/all/Packages.gz.
Mon Jan 22 17:27:23 2024: Updated source 'all'.
Mon Jan 22 17:27:23 2024: Downloading https://updates.victronenergy.com/feeds/venus/release/packages/dunfell/cortexa7hf-neon-vfpv4/Packages.gz.
Mon Jan 22 17:27:25 2024: Updated source 'cortexa7hf-neon-vfpv4'.
Mon Jan 22 17:27:25 2024: Downloading https://updates.victronenergy.com/feeds/venus/release/packages/dunfell/nanopi/Packages.gz.
Mon Jan 22 17:27:26 2024: Updated source 'nanopi'.
Mon Jan 22 17:27:35 2024: No packages installed or removed.
Mon Jan 22 17:28:01 2024: Collecting bleak
Mon Jan 22 17:28:01 2024:   Using cached bleak-0.21.1-py3-none-any.whl (137 kB)
Mon Jan 22 17:28:29 2024: Collecting dbus-fast<3,>=1.83.0; platform_system == "Linux"
Mon Jan 22 17:28:29 2024:   Using cached dbus_fast-2.21.1.tar.gz (69 kB)
Mon Jan 22 17:28:43 2024:   Installing build dependencies ... ?done
Mon Jan 22 17:29:27 2024: ?  Getting requirements to build wheel ... ?done
Mon Jan 22 17:29:31 2024: ?    Preparing wheel metadata ... ?done
Mon Jan 22 17:29:32 2024: ?Collecting typing-extensions>=4.7.0; python_version < "3.12"
Mon Jan 22 17:29:32 2024:   Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Mon Jan 22 17:29:33 2024: Collecting async-timeout<5,>=3.0.0; python_version < "3.11"
Mon Jan 22 17:29:33 2024:   Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Mon Jan 22 17:29:33 2024: Building wheels for collected packages: dbus-fast
Mon Jan 22 17:29:37 2024:   Building wheel for dbus-fast (PEP 517)`

There it hangs

/data/log/dbus-blebattery.0/current:
`@4000000065ae9b8f1bd96ec4 INFO:SerialBattery:Starting dbus-serialbattery
@4000000065ae9b8f1bd9a18c INFO:SerialBattery:dbus-serialbattery v1.0.20230531
@4000000065ae9b9605e11aa4
@4000000065ae9b961da33dfc Traceback (most recent call last):
@4000000065ae9b961da368f4   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 163, in <module>
@4000000065ae9b961da37894     main()
@4000000065ae9b961da38064   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 120, in main
@4000000065ae9b961da38c1c     from bms.jkbms_ble import Jkbms_Ble  # noqa: F401
@4000000065ae9b961da397d4   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_ble.py", line 4, in <module>
@4000000065ae9b961dcd47b4     from bms.jkbms_brn import Jkbms_Brn
@4000000065ae9b961dcd630c   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_brn.py", line 2, in <module>
@4000000065ae9b961dcd7694     from bleak import BleakScanner, BleakClient
@4000000065ae9b961dcd7e64 ModuleNotFoundError: No module named 'bleak'
@4000000065ae9b983577fef4 Missing device address argument`

If i try to install bleak with 
"pip3 install bleak"

the systems reboots after some time

### Driver version

 v1.0.20230531

### Venus OS device type

GX Card (integrated in Victron device)

### Venus OS version

v3.13

### BMS type

JKBMS / Heltec BMS

### Cell count

16

### Battery count

1

### Connection type

Bluetooth

### Config file

```ini
Default!

Changed 
BLUETOOTH_BMS = Jkbms_Ble E1:84:C1:xx:xx:xx   (my Mac censored! ;-))
```

### Relevant log output

```shell
2024-01-22 16:44:31.655157500 Traceback (most recent call last):
2024-01-22 16:44:31.655170500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 163, in <module>
2024-01-22 16:44:31.655175500     main()
2024-01-22 16:44:31.655177500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 120, in main
2024-01-22 16:44:31.655181500     from bms.jkbms_ble import Jkbms_Ble  # noqa: F401
2024-01-22 16:44:31.655184500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_ble.py", line 4, in <module>
2024-01-22 16:44:31.655367500     from bms.jkbms_brn import Jkbms_Brn
2024-01-22 16:44:31.655372500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_brn.py", line 2, in <module>
2024-01-22 16:44:31.655376500     from bleak import BleakScanner, BleakClient
2024-01-22 16:44:31.655379500 ModuleNotFoundError: No module named 'bleak'
2024-01-22 16:44:33.356655500 Missing device address argument
2024-01-22 16:44:53.467234500 INFO:SerialBattery:Starting dbus-serialbattery
2024-01-22 16:44:53.467247500 INFO:SerialBattery:dbus-serialbattery v1.0.20230531
2024-01-22 16:45:00.098638500
2024-01-22 16:45:00.497237500 Traceback (most recent call last):
2024-01-22 16:45:00.497248500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 163, in <module>
2024-01-22 16:45:00.497252500     main()
2024-01-22 16:45:00.497254500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 120, in main
2024-01-22 16:45:00.497257500     from bms.jkbms_ble import Jkbms_Ble  # noqa: F401
2024-01-22 16:45:00.497260500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_ble.py", line 4, in <module>
2024-01-22 16:45:00.499992500     from bms.jkbms_brn import Jkbms_Brn
2024-01-22 16:45:00.499999500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_brn.py", line 2, in <module>
2024-01-22 16:45:00.500004500     from bleak import BleakScanner, BleakClient
2024-01-22 16:45:00.500006500 ModuleNotFoundError: No module named 'bleak'
2024-01-22 16:45:02.897056500 Missing device address argument
2024-01-22 16:47:30.664015500 *** CCGX booted (30253) ***
2024-01-22 16:56:50.731396500 *** CCGX booted (30012) ***
2024-01-22 17:07:28.646298500 *** CCGX booted (30253) ***
2024-01-22 17:16:49.664449500 *** CCGX booted (30012) ***
2024-01-22 17:27:11.669438500 *** CCGX booted (30012) ***
2024-01-22 17:39:09.705868500 *** CCGX booted (30253) ***
```

**Comment by mr-manuel** [comment]
![IMG_2255](https://github.com/Louisvdw/dbus-serialbattery/assets/12592765/58bb7a2c-3d72-4181-adf7-fd60cfa3d257)
