### ISSUE TITLE
Driver restart in a loop

### ISSUE THREAD

**Issue by rechin304** [Louisvdw/dbus-serialbattery#943]
### Describe the bug

Driver keeps restarting.

Is keep doing that in a loop

### How to reproduce

 Fresh installation id doing this from start, tried dev still same issue. 

### Expected behavior

 Data to be displayed.

### Driver version

v1.0.20230531

### Venus OS device type

Raspberry Pi 3

### Venus OS version

3.14

### BMS type

Life/Tian Power

### Cell count

16

### Battery count

1

### Connection type

Serial USB adapter to RS485

### Config file

```ini
[DEFAULT]

; If you want to add custom values/settings, then check the values/settings you want to change in "config.default.ini"
; and insert them below to persist future driver updates.

; Example (remove the semicolon ";" to uncomment and activate the value/setting):
MAX_BATTERY_CHARGE_CURRENT = 50.0
MAX_BATTERY_DISCHARGE_CURRENT = 80.0
```

### Relevant log output

```shell
2024-01-29 05:12:54.511795500 INFO:SerialBattery:Starting dbus-serialbattery
2024-01-29 05:12:54.512794500 INFO:SerialBattery:dbus-serialbattery v1.0.20230531
2024-01-29 05:12:54.513247500 INFO:SerialBattery:Testing Lifepower
2024-01-29 05:12:55.189539500 ERROR:SerialBattery:Unexpected err=error('unpack_from requires a buffer of at least 106 bytes for unpacking 2 bytes at offset 104 (actual buffer size is 105)'), type(err)=<class 'struct.error'>
2024-01-29 05:12:55.690816500 INFO:SerialBattery:Testing Lifepower
2024-01-29 05:12:55.954278500 INFO:SerialBattery:Connection established to Lifepower
2024-01-29 05:12:55.954778500 INFO:SerialBattery:Battery EG4 Lifepower connected to dbus from /dev/ttyUSB0
2024-01-29 05:12:55.955221500 INFO:SerialBattery:========== Settings ==========
2024-01-29 05:12:55.955744500 INFO:SerialBattery:> Connection voltage: 51.24V | Current: -1.44A | SoC: 31.42%
2024-01-29 05:12:55.956166500 INFO:SerialBattery:> Cell count: 16 | Cells populated: 16
2024-01-29 05:12:55.956598500 INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
2024-01-29 05:12:55.957047500 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 50.0A | MAX BATTERY DISCHARGE CURRENT: 80.0A
2024-01-29 05:12:55.957480500 INFO:SerialBattery:> CVCM:     True
2024-01-29 05:12:55.957936500 INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.45V
2024-01-29 05:12:55.958365500 INFO:SerialBattery:> CCCM CV:  True  | DCCM CV:  True
2024-01-29 05:12:55.958793500 INFO:SerialBattery:> CCCM T:   True  | DCCM T:   True
2024-01-29 05:12:55.959292500 INFO:SerialBattery:> CCCM SOC: True  | DCCM SOC: True
2024-01-29 05:12:56.015543500 INFO:SerialBattery:DeviceInstance = 2
2024-01-29 05:12:56.016043500 INFO:SerialBattery:com.victronenergy.battery.ttyUSB0
2024-01-29 05:12:56.059800500 INFO:SerialBattery:Hardware Version:BTBI23090100087 
2024-01-29 05:12:56.115036500 INFO:SerialBattery:Firmware Version:3BN-HES16S48V100LT52-V1.3.1
2024-01-29 05:12:56.150251500 INFO:SerialBattery:publish config values = 1
2024-01-29 05:13:06.869879500 Traceback (most recent call last):
2024-01-29 05:13:06.869886500   File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 361, in publish_battery
2024-01-29 05:13:06.869891500     success = self.battery.refresh_data()
2024-01-29 05:13:06.869894500   File "/opt/victronenergy/dbus-serialbattery/bms/lifepower.py", line 70, in refresh_data
2024-01-29 05:13:06.869899500     return self.read_status_data()
2024-01-29 05:13:06.869902500   File "/opt/victronenergy/dbus-serialbattery/bms/lifepower.py", line 87, in read_status_data
2024-01-29 05:13:06.880647500     group_len = status_data[i + 1]
2024-01-29 05:13:06.880652500 IndexError: bytearray index out of range
2024-01-29 05:13:06.880744500
```

**Comment by rechin304** [comment]
Changing the USB cable solved the issue.
