### ISSUE TITLE
JK BMS connects for a short time and disconnects

### ISSUE THREAD

**Issue by seamaster101** [Louisvdw/dbus-serialbattery#948]
### Describe the problem

I have 4 JK BMSs and i first connected one. It showed up on the display but then in few seconds it disappears. I tried to troubleshoot and the log shows maybe some crash

what is the issue? what should I do next?

### Driver version

1.0.20230531

### Venus OS device type

Please select

### Venus OS version

v3.20~45

### BMS type

JKBMS / Heltec BMS

### Cell count

4

### Battery count

4

### Connection type

Please select

### Config file

```ini
original - not changed
```

### Relevant log output

```shell
`2024-02-04 08:38:11.504443500 INFO:SerialBattery:Battery Jkbms connected to dbus from /dev/ttyUSB5
2024-02-04 08:38:11.504934500 INFO:SerialBattery:========== Settings ==========
2024-02-04 08:38:11.505413500 INFO:SerialBattery:> Connection voltage: 13.22V | Current: 4.28A | SoC: 96%
2024-02-04 08:38:11.505825500 INFO:SerialBattery:> Cell count: 4 | Cells populated: 0
2024-02-04 08:38:11.506256500 INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
2024-02-04 08:38:11.506698500 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 50.0A | MAX BATTERY DISCHARGE CURRENT: 60.0A
2024-02-04 08:38:11.507135500 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 150.0A | MAX BATTERY DISCHARGE CURRENT: 200.0A (read from BMS)
2024-02-04 08:38:11.507556500 INFO:SerialBattery:> CVCM:     True
2024-02-04 08:38:11.507991500 INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.45V
2024-02-04 08:38:11.508422500 INFO:SerialBattery:> CCCM CV:  True  | DCCM CV:  True
2024-02-04 08:38:11.508852500 INFO:SerialBattery:> CCCM T:   True  | DCCM T:   True
2024-02-04 08:38:11.509392500 INFO:SerialBattery:> CCCM SOC: True  | DCCM SOC: True
2024-02-04 08:38:11.509810500 INFO:SerialBattery:Serial Number/Unique Identifier: HB1_B1
2024-02-04 08:38:11.562421500 INFO:SerialBattery:DeviceInstance = 1
2024-02-04 08:38:11.563096500 INFO:SerialBattery:com.victronenergy.battery.ttyUSB5
2024-02-04 08:38:11.587907500 INFO:SerialBattery:publish config values = 1
2024-02-04 08:39:34.737410500 Traceback (most recent call last):
2024-02-04 08:39:34.737417500   File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 361, in publish_battery
2024-02-04 08:39:34.737422500     success = self.battery.refresh_data()
2024-02-04 08:39:34.737425500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms.py", line 54, in refresh_data
2024-02-04 08:39:34.737430500     result = self.read_status_data()
2024-02-04 08:39:34.737433500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms.py", line 67, in read_status_data
2024-02-04 08:39:34.737560500     status_data = self.read_serial_data_jkbms(self.command_status)
2024-02-04 08:39:34.737565500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms.py", line 314, in read_serial_data_jkbms
2024-02-04 08:39:34.737570500     data = read_serial_data(
2024-02-04 08:39:34.737573500   File "/opt/victronenergy/dbus-serialbattery/utils.py", line 421, in read_serial_data
2024-02-04 08:39:34.737578500     with serial.Serial(port, baudrate=baud, timeout=0.1) as ser:
2024-02-04 08:39:34.737605500   File "/usr/lib/python3.8/site-packages/serial/serialutil.py", line 240, in __init__
2024-02-04 08:39:34.737610500     self.open()
2024-02-04 08:39:34.737612500   File "/usr/lib/python3.8/site-packages/serial/serialposix.py", line 288, in open
2024-02-04 08:39:34.737617500     self._update_rts_state()
2024-02-04 08:39:34.737619500   File "/usr/lib/python3.8/site-packages/serial/serialposix.py", line 627, in _update_rts_state
2024-02-04 08:39:34.737674500     fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_RTS_str)
2024-02-04 08:39:34.737678500 OSError: [Errno 71] Protocol error
2024-02-04 08:39:34.737680500
2024-02-04 08:39:57.615107500 INFO:SerialBattery:Starting dbus-serialbattery
2024-02-04 08:39:57.616697500 INFO:SerialBattery:dbus-serialbattery v1.0.20230531
2024-02-04 08:39:57.617155500 INFO:SerialBattery:Testing Daly
2024-02-04 08:39:57.744491500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:39:57.745100500 INFO:SerialBattery:Testing Daly
2024-02-04 08:39:57.870820500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:39:57.871306500 INFO:SerialBattery:Testing Ecs
2024-02-04 08:39:57.932630500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:39:57.933148500 INFO:SerialBattery:Testing HeltecModbus
2024-02-04 08:40:00.815632500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:40:00.816206500 INFO:SerialBattery:Testing HLPdataBMS4S
2024-02-04 08:40:05.326550500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:40:05.327064500 INFO:SerialBattery:Testing Jkbms
2024-02-04 08:40:05.450287500 INFO:SerialBattery:Connection established to Jkbms
2024-02-04 08:40:05.450824500 INFO:SerialBattery:Battery Jkbms connected to dbus from /dev/ttyUSB5
2024-02-04 08:40:05.451233500 INFO:SerialBattery:========== Settings ==========
2024-02-04 08:40:05.451711500 INFO:SerialBattery:> Connection voltage: 13.23V | Current: 2.23A | SoC: 96%
2024-02-04 08:40:05.452127500 INFO:SerialBattery:> Cell count: 4 | Cells populated: 0
2024-02-04 08:40:05.452559500 INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
2024-02-04 08:40:05.453008500 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 50.0A | MAX BATTERY DISCHARGE CURRENT: 60.0A
2024-02-04 08:40:05.453448500 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 150.0A | MAX BATTERY DISCHARGE CURRENT: 200.0A (read from BMS)
2024-02-04 08:40:05.453863500 INFO:SerialBattery:> CVCM:     True
2024-02-04 08:40:05.454306500 INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.45V
2024-02-04 08:40:05.454903500 INFO:SerialBattery:> CCCM CV:  True  | DCCM CV:  True
2024-02-04 08:40:05.455481500 INFO:SerialBattery:> CCCM T:   True  | DCCM T:   True
2024-02-04 08:40:05.455931500 INFO:SerialBattery:> CCCM SOC: True  | DCCM SOC: True
2024-02-04 08:40:05.456339500 INFO:SerialBattery:Serial Number/Unique Identifier: HB1_B1
2024-02-04 08:40:05.513403500 INFO:SerialBattery:DeviceInstance = 1
2024-02-04 08:40:05.514659500 INFO:SerialBattery:com.victronenergy.battery.ttyUSB5
2024-02-04 08:40:05.543856500 INFO:SerialBattery:publish config values = 1
2024-02-04 08:40:47.641075500 Traceback (most recent call last):
2024-02-04 08:40:47.641081500   File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 361, in publish_battery
2024-02-04 08:40:47.641086500     success = self.battery.refresh_data()
2024-02-04 08:40:47.641089500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms.py", line 54, in refresh_data
2024-02-04 08:40:47.641094500     result = self.read_status_data()
2024-02-04 08:40:47.641097500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms.py", line 67, in read_status_data
2024-02-04 08:40:47.641221500     status_data = self.read_serial_data_jkbms(self.command_status)
2024-02-04 08:40:47.641225500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms.py", line 314, in read_serial_data_jkbms
2024-02-04 08:40:47.641231500     data = read_serial_data(
2024-02-04 08:40:47.641233500   File "/opt/victronenergy/dbus-serialbattery/utils.py", line 421, in read_serial_data
2024-02-04 08:40:47.641238500     with serial.Serial(port, baudrate=baud, timeout=0.1) as ser:
2024-02-04 08:40:47.641269500   File "/usr/lib/python3.8/site-packages/serial/serialutil.py", line 240, in __init__
2024-02-04 08:40:47.641274500     self.open()
2024-02-04 08:40:47.641276500   File "/usr/lib/python3.8/site-packages/serial/serialposix.py", line 288, in open
2024-02-04 08:40:47.641280500     self._update_rts_state()
2024-02-04 08:40:47.641283500   File "/usr/lib/python3.8/site-packages/serial/serialposix.py", line 627, in _update_rts_state
2024-02-04 08:40:47.641337500     fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_RTS_str)
2024-02-04 08:40:47.641341500 OSError: [Errno 71] Protocol error
2024-02-04 08:40:47.641343500
2024-02-04 08:41:07.049209500 INFO:SerialBattery:Starting dbus-serialbattery
2024-02-04 08:41:07.050273500 INFO:SerialBattery:dbus-serialbattery v1.0.20230531
2024-02-04 08:41:07.055255500 INFO:SerialBattery:Testing Daly
2024-02-04 08:41:07.177943500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:07.178422500 INFO:SerialBattery:Testing Daly
2024-02-04 08:41:07.304703500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:07.305332500 INFO:SerialBattery:Testing Ecs
2024-02-04 08:41:07.366760500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:07.367339500 INFO:SerialBattery:Testing HeltecModbus
2024-02-04 08:41:11.046598500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:11.047240500 INFO:SerialBattery:Testing HLPdataBMS4S
2024-02-04 08:41:15.558727500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:15.559233500 INFO:SerialBattery:Testing Jkbms
2024-02-04 08:41:15.833754500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:15.834989500 INFO:SerialBattery:Testing Lifepower
2024-02-04 08:41:16.109125500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:16.110053500 INFO:SerialBattery:Testing LltJbd
2024-02-04 08:41:16.383645500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:16.384721500 INFO:SerialBattery:Testing Renogy
2024-02-04 08:41:16.654456500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:16.655593500 INFO:SerialBattery:Testing Renogy
2024-02-04 08:41:16.923451500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:16.924752500 INFO:SerialBattery:Testing Seplos
2024-02-04 08:41:17.932789500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:18.434549500 INFO:SerialBattery:Testing Daly
2024-02-04 08:41:18.560630500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:18.561129500 INFO:SerialBattery:Testing Daly
2024-02-04 08:41:18.687012500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:18.687497500 INFO:SerialBattery:Testing Ecs
2024-02-04 08:41:19.097320500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:19.097868500 INFO:SerialBattery:Testing HeltecModbus
2024-02-04 08:41:22.774981500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:22.775442500 INFO:SerialBattery:Testing HLPdataBMS4S
2024-02-04 08:41:27.286658500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:41:27.287128500 INFO:SerialBattery:Testing Jkbms
2024-02-04 08:41:27.411138500 INFO:SerialBattery:Connection established to Jkbms
2024-02-04 08:41:27.411789500 INFO:SerialBattery:Battery Jkbms connected to dbus from /dev/ttyUSB5
2024-02-04 08:41:27.412310500 INFO:SerialBattery:========== Settings ==========
2024-02-04 08:41:27.412878500 INFO:SerialBattery:> Connection voltage: 13.23V | Current: 1.86A | SoC: 96%
2024-02-04 08:41:27.413516500 INFO:SerialBattery:> Cell count: 4 | Cells populated: 0
2024-02-04 08:41:27.414061500 INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
2024-02-04 08:41:27.414762500 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 50.0A | MAX BATTERY DISCHARGE CURRENT: 60.0A
2024-02-04 08:41:27.415372500 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 150.0A | MAX BATTERY DISCHARGE CURRENT: 200.0A (read from BMS)
2024-02-04 08:41:27.415899500 INFO:SerialBattery:> CVCM:     True
2024-02-04 08:41:27.416444500 INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.45V
2024-02-04 08:41:27.416975500 INFO:SerialBattery:> CCCM CV:  True  | DCCM CV:  True
2024-02-04 08:41:27.417501500 INFO:SerialBattery:> CCCM T:   True  | DCCM T:   True
2024-02-04 08:41:27.418025500 INFO:SerialBattery:> CCCM SOC: True  | DCCM SOC: True
2024-02-04 08:41:27.418534500 INFO:SerialBattery:Serial Number/Unique Identifier: HB1_B1
2024-02-04 08:41:27.466193500 INFO:SerialBattery:DeviceInstance = 1
2024-02-04 08:41:27.467017500 INFO:SerialBattery:com.victronenergy.battery.ttyUSB5
2024-02-04 08:41:27.486976500 INFO:SerialBattery:publish config values = 1
2024-02-04 08:41:58.569081500 Traceback (most recent call last):
2024-02-04 08:41:58.569087500   File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 361, in publish_battery
2024-02-04 08:41:58.569093500     success = self.battery.refresh_data()
2024-02-04 08:41:58.569096500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms.py", line 54, in refresh_data
2024-02-04 08:41:58.569100500     result = self.read_status_data()
2024-02-04 08:41:58.569103500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms.py", line 67, in read_status_data
2024-02-04 08:41:58.569225500     status_data = self.read_serial_data_jkbms(self.command_status)
2024-02-04 08:41:58.569230500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms.py", line 314, in read_serial_data_jkbms
2024-02-04 08:41:58.569235500     data = read_serial_data(
2024-02-04 08:41:58.569238500   File "/opt/victronenergy/dbus-serialbattery/utils.py", line 421, in read_serial_data
2024-02-04 08:41:58.569243500     with serial.Serial(port, baudrate=baud, timeout=0.1) as ser:
2024-02-04 08:41:58.569330500   File "/usr/lib/python3.8/site-packages/serial/serialutil.py", line 240, in __init__
2024-02-04 08:41:58.569336500     self.open()
2024-02-04 08:41:58.569338500   File "/usr/lib/python3.8/site-packages/serial/serialposix.py", line 288, in open
2024-02-04 08:41:58.569342500     self._update_rts_state()
2024-02-04 08:41:58.569345500   File "/usr/lib/python3.8/site-packages/serial/serialposix.py", line 627, in _update_rts_state
2024-02-04 08:41:58.569398500     fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_RTS_str)
2024-02-04 08:41:58.569402500 OSError: [Errno 71] Protocol error
2024-02-04 08:41:58.569404500
2024-02-04 08:42:21.548302500 INFO:SerialBattery:Starting dbus-serialbattery
2024-02-04 08:42:21.549294500 INFO:SerialBattery:dbus-serialbattery v1.0.20230531
2024-02-04 08:42:21.549745500 INFO:SerialBattery:Testing Daly
2024-02-04 08:42:21.676841500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:21.677348500 INFO:SerialBattery:Testing Daly
2024-02-04 08:42:21.802761500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:21.803250500 INFO:SerialBattery:Testing Ecs
2024-02-04 08:42:21.863747500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:21.864228500 INFO:SerialBattery:Testing HeltecModbus
2024-02-04 08:42:25.540337500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:25.540796500 INFO:SerialBattery:Testing HLPdataBMS4S
2024-02-04 08:42:30.052395500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:30.052900500 INFO:SerialBattery:Testing Jkbms
2024-02-04 08:42:30.064293500 ERROR:SerialBattery:Unexpected err=OSError(71, 'Protocol error'), type(err)=<class 'OSError'>
2024-02-04 08:42:30.065415500 INFO:SerialBattery:Testing Lifepower
2024-02-04 08:42:30.338179500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:30.339150500 INFO:SerialBattery:Testing LltJbd
2024-02-04 08:42:30.624341500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:30.625443500 INFO:SerialBattery:Testing Renogy
2024-02-04 08:42:30.894207500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:30.895936500 INFO:SerialBattery:Testing Renogy
2024-02-04 08:42:31.167607500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:31.168539500 INFO:SerialBattery:Testing Seplos
2024-02-04 08:42:32.176267500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:32.677554500 INFO:SerialBattery:Testing Daly
2024-02-04 08:42:32.803971500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:32.804578500 INFO:SerialBattery:Testing Daly
2024-02-04 08:42:32.930145500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:32.930637500 INFO:SerialBattery:Testing Ecs
2024-02-04 08:42:33.340213500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:33.340673500 INFO:SerialBattery:Testing HeltecModbus
2024-02-04 08:42:37.025533500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2024-02-04 08:42:37.026177500 INFO:SerialBattery:Testing HLPdataBMS4S`
```

### Any other information that may be helpful

no

**Comment by mr-manuel** [comment]
![303372193-a6814b33-f613-41b9-a612-f7a28d213f66](https://github.com/Louisvdw/dbus-serialbattery/assets/12592765/cf2df559-ce87-4235-895c-4a09ae583e31)
