### ISSUE TITLE
BLE JKBMS not more working after update. Module named 'bleak'

### ISSUE THREAD

**Issue by githubfrance** [Louisvdw/dbus-serialbattery#990]
### Describe the problem

HI,
On raspberry after upgrade to Venus OS 3.20 Build 20240213074236 the JKBMS BLE is not working anymore. I uninsalled and reinstalled  beta build "v1.2.20240219beta" (mr-manuel's repo, no errors after 72 h runtime, long time testing needed) with nos success. The only significant error is ModuleNotFoundError: No module named 'bleak'.
Thank you for any feedback

### Driver version

v1.2.20240219beta

### Venus OS device type

Raspberry Pi

### Venus OS version

3.20

### BMS type

JKBMS / Heltec BMS

### Cell count

4

### Battery count

2

### Connection type

Bluetooth

### Config file

```ini
[DEFAULT]

; --------- Set logging level ---------
; ERROR: Only errors are logged
; WARNING: Errors and warnings are logged
; INFO: Errors, warnings and info messages are logged
; DEBUG: Errors, warnings, info and debug messages are logged
LOGGING = INFO


; --------- Battery Current limits ---------
MAX_BATTERY_CHARGE_CURRENT    = 100.0
MAX_BATTERY_DISCHARGE_CURRENT = 200.0


; --------- Cell Voltages ---------
; Description:
;     Cell min/max voltages which are used to calculate the min/max battery voltage
; Example:
;     16 cells * 3.45V/cell = 55.2V max charge voltage. 16 cells * 2.90V = 46.4V min discharge voltage
MIN_CELL_VOLTAGE   = 2.900
; Max voltage (can seen as absorption voltage)
MAX_CELL_VOLTAGE   = 3.600
; Float voltage (can be seen as resting voltage)
FLOAT_CELL_VOLTAGE = 3.45


; --------- SOC reset voltage ---------
; Description:
;     May be needed to reset the SoC to 100% once in a while for some BMS, because of SoC drift.
;     Specify the cell voltage where the SoC should be reset to 100% by the BMS.
;       - JKBMS: SoC is reset to 100% if one cell reaches OVP (over voltage protection) voltage
;     As you have to adopt this value to your system, I reccomend to start with
;     OVP voltage - 0.030 (see Example).
;       - Try to increase (add) by 0.005 in steps, if the system does not switch to float mode, even if
;         the target voltage SOC_RESET_VOLTAGE * CELL_COUNT is reached.
;       - Try to decrease (lower) by 0.005 in steps, if the system hits the OVP too fast, before all
;         cells could be balanced and the system goes into protection mode multiple times.
; Example:
;     If OVP is 3.650, then start with 3.620 and increase/decrease by 0.005
; Note:
;     The value has to be higher as the MAX_CELL_VOLTAGE
SOC_RESET_VOLTAGE = 3.65
; Specify after how many days the soc reset voltage should be reached again
; The timer is reset when the soc reset voltage is reached
; Leave empty if you don't want to use this
; Example:
;     Value is set to 15
;     day 1: soc reset reached once
;     day 16: soc reset reached twice
;     day 31: soc reset not reached since it's very cloudy
;     day 34: soc reset reached since the sun came out
;     day 49: soc reset reached again, since last time it took 3 days to reach soc reset voltage
SOC_RESET_AFTER_DAYS =


; --------- Bluetooth BMS ---------
; Description:
;     Specify the Bluetooth BMS and it's MAC address that you want to install. Leave emty to disable
; Available Bluetooth BMS:
;     Jkbms_Ble, LltJbd_Ble
; Example for one BMS:
;     BLUETOOTH_BMS = Jkbms_Ble C8:47:8C:00:00:00
; Example for multiple BMS:
;     BLUETOOTH_BMS = Jkbms_Ble C8:47:8C:00:00:00, Jkbms_Ble C8:47:8C:00:00:11, Jkbms_Ble C8:47:8C:00:00:22
BLUETOOTH_BMS = Jkbms_Ble C8:47:8C:ED:06:11


; --------- Bluetooth use USB ---------
; Description:  Some users reported issues to the built in bluetooth module, you can try to fix it with an USB
;     module. After a change you have to run reinstall-local.sh and to manual reboot the device!
;     The usb bluetooth module must have BLE support (bluetooth version >= 4.0)
;     Other bluetooth devices such as Ruuvi tags not tested yet.
; False: Use the built in bluetooth module
; True: Disable built in bluetooth module and try to use USB module
BLUETOOTH_USE_USB = False


; --------- CAN BMS ---------
; Description:
;     Specify the CAN port(s) where the BMS is connected to. Leave empty to disable
; Available CAN BMS:
;     Daly_Can, Jkbms_Can
; Example for one CAN port:
;     CAN_PORT = can0
; Example for multiple CAN ports:
;     CAN_PORT = can0, can8, can9
CAN_PORT =


; --------- BMS disconnect behaviour ---------
; Description:
;     Block charge and discharge when the communication to the BMS is lost. If you are removing the
;     BMS on purpose, then you have to restart the driver/system to reset the block.
; False:
;     Charge and discharge is not blocked on BMS communication loss for 20 minutes, if cell voltages are between
;     3.25 V and 3.35 V. Else the driver block charge and discharge after 60 seconds.
; True:
;     Charge and discharge is blocked on BMS communication loss, it's unblocked when connection is established
;     again or the driver/system is restarted. This is the Victron Energy default behaviour.
BLOCK_ON_DISCONNECT = False


; --------- Charge mode ---------
; Choose the mode for voltage / current limitations (True / False)
; False is a step mode: This is the default with limitations on hard boundary steps
; True is a linear mode:
;     For CCL and DCL the values between the steps are calculated for smoother values (by WaldemarFech)
;     For CVL max battery voltage is calculated dynamically in order that the max cell voltage is not exceeded
LINEAR_LIMITATION_ENABLE = True

; Specify in seconds how often the linear values should be recalculated
LINEAR_RECALCULATION_EVERY = 60
; Specify in percent when the linear values should be recalculated immediately
; Example:
;     5 for a immediate change, when the value changes by more than 5%
LINEAR_RECALCULATION_ON_PERC_CHANGE = 5


; --------- Charge Voltage limitation (affecting CVL) ---------
; Description:
;     Limit max charging voltage (MAX_CELL_VOLTAGE * cell count), switch from max voltage to float
;     voltage (FLOAT_CELL_VOLTAGE * cell count) and back
;     False: Max charging voltage is always kept
;     True: Max charging voltage is reduced based on charge mode
;         Step mode: After max voltage is reached for MAX_VOLTAGE_TIME_SEC it switches to float voltage. After
;             SoC is below SOC_LEVEL_TO_RESET_VOLTAGE_LIMIT it switches back to max voltage.
;         Linear mode: After max voltage is reachend and cell voltage difference is smaller or equal to
;             CELL_VOLTAGE_DIFF_KEEP_MAX_VOLTAGE_UNTIL it switches to float voltage after MAX_VOLTAGE_TIME_SEC
;             additional seconds.
;             After cell voltage difference is greater or equal to CELL_VOLTAGE_DIFF_TO_RESET_VOLTAGE_LIMIT
;             OR
;             SoC is below SOC_LEVEL_TO_RESET_VOLTAGE_LIMIT
;             it switches back to max voltage.
; Example when set to True:
;     Step mode:
;          The battery reached max voltage of 55.2V and hold it for 900 seconds, the the CVL is switched to
;          float voltage of 53.6V to don't stress the batteries. Allow max voltage of 55.2V again, if SoC is
;          once below 80%
;     Linear mode:
;          The battery reached max voltage of 55.2V and the max cell difference is 0.010V, then switch to float
;          voltage of 53.6V after 900 additional seconds to don't stress the batteries. Allow max voltage of
;          55.2V again if max cell difference is above 0.080V or SoC below 80%.
; Charge voltage control management enable (True/False).
CVCM_ENABLE = True

; -- CVL reset based on cell voltage diff (linear mode)
; Specify cell voltage diff where CVL limit is kept until diff is equal or lower
CELL_VOLTAGE_DIFF_KEEP_MAX_VOLTAGE_UNTIL        = 0.010
; Specify cell voltage diff where MAX_VOLTAGE_TIME_SEC restarts if diff is bigger
CELL_VOLTAGE_DIFF_KEEP_MAX_VOLTAGE_TIME_RESTART = 0.013
; Specify cell voltage diff where CVL limit is reset to max voltage, if value get above
; the cells are considered as imbalanced, if the cell diff exceeds 5% of the nominal cell voltage
; e.g. 3.2 V * 5 / 100 = 0.160 V
CELL_VOLTAGE_DIFF_TO_RESET_VOLTAGE_LIMIT        = 0.080

; -- CVL reset based on SoC option (step mode & linear mode)
; Specify how long the max voltage should be kept
;     Step mode: If reached then switch to float voltage
;     Linear mode: If cells are balanced keep max voltage for further MAX_VOLTAGE_TIME_SEC seconds
MAX_VOLTAGE_TIME_SEC = 900
; Specify SoC where CVL limit is reset to max voltage
;     Step mode: If SoC gets below
;     Linear mode: If cells are unbalanced or if SoC gets below
SOC_LEVEL_TO_RESET_VOLTAGE_LIMIT = 80


; --------- SOC calculation ---------
; Description:
;     Calculate the SOC in the driver. Do not use the SOC reported by the BMS
; SOC_CALCULATION:
;     True: Calc SOC in the driver, do not use SOC reported from BMS
;         - The SOC is calculated by integration of the current reported by the BMS
;         - The current reported from the BMS can be corrected by
;           the map (SOC_CALC_CURRENT_REPORTED_BY_BMS, SOC_CALC_CURRENT_MEASURED_BY_USER)
;         - The SOC is set to 100% if the following conditions apply for at least SOC_RESET_TIME seconds:
;             * Current is lower than SOC_RESET_CURRENT amps
;             * Sum of cell voltages >= self.max_battery_voltage - VOLTAGE_DROP
;         - The calculated SOC is stored in dbus to persist a driver restart
;     False: Use SOC reported from BMS (none of the other parameters apply)
; More info: https://github.com/Louisvdw/dbus-serialbattery/pull/868
SOC_CALCULATION   = False
SOC_RESET_CURRENT = 7
SOC_RESET_TIME    = 60
SOC_CALC_CURRENT_REPORTED_BY_BMS  = -300, 300
SOC_CALC_CURRENT_MEASURED_BY_USER = -300, 300
; Example to set small currents to zero
;     SOC_CALC_CURRENT_REPORTED_BY_BMS  = -300, -0.5, 0.5, 300
;     SOC_CALC_CURRENT_MEASURED_BY_USER = -300,    0,   0, 300


; --------- Cell Voltage Current limitation (affecting CCL/DCL) ---------
; Description: Maximal charge / discharge current will be in-/decreased depending on min and max cell voltages
; Example:
;     18 cells * 3.55V/cell = 63.9V max charge voltage
;     18 cells * 2.70V/cell = 48.6V min discharge voltage
;     But in reality not all cells reach the same voltage at the same time. The (dis)charge current
;     will be (in-/)decreased, if even ONE SINGLE BATTERY CELL reaches the limits

; Charge current control management referring to cell-voltage enable (True/False).
CCCM_CV_ENABLE = True
; Discharge current control management referring to cell-voltage enable (True/False).
DCCM_CV_ENABLE = True

; Set steps to reduce battery current
; The current will be changed linear between those steps if LINEAR_LIMITATION_ENABLE is set to True
CELL_VOLTAGES_WHILE_CHARGING      = 3.65, 3.50, 3.45, 3.30
MAX_CHARGE_CURRENT_CV_FRACTION    =    0, 0.05,  0.5,    1

CELL_VOLTAGES_WHILE_DISCHARGING   = 2.70, 2.80, 2.90, 3.10
MAX_DISCHARGE_CURRENT_CV_FRACTION =    0,  0.1,  0.5,    1


; --------- Cell Voltage limitation (affecting CVL) ---------
; This function prevents a bad balanced battery to overcharge the cell with the highest voltage and the bms to
; switch off because of overvoltage of this cell.
;
; Example:
;     15 cells are at 3.4v, 1 cell is at 3.6v. Total voltage of battery is 54.6v and the Victron System sees no reason to
;     lower the charging current as the control_voltage (Absorbtion Voltage) ist 55.2v
;     In this case the Cell Voltage limitation kicks in and lowers the control_voltage to keep it close to the MAX_CELL_VOLTAGE.
;
; In theory this can also be done with CCL, but doing it with CVL has 2 advantages:
;     - In a well balanced system the current can be kept quite high till the end of charge by using MAX_CELL_VOLTAGE for charging.
;     - In systems with MPPTs and DC-feed-in activated the victron systems do not respect CCL, so CVL is the only way to prevent the
;       highest cell in a bad balanced system from overcharging.
;
; There are 2 methods implemented to calculate CVL:
;   1. penalty_sum-Method (CVL_ICONTROLLER_MODE = False)
;      The voltage-overshoot of all cells that exceed MAX_CELL_VOLTAGE is summed up and the control voltage is lowered by this "penalty_sum".
;      This is calculated every LINEAR_RECALCULATION_EVERY seconds.
;      In fact, this is a P-Controller.
;   2. I-Controller (CVL_ICONTROLLER_MODE = True)
;      An I-Controller tries to control the voltage of the highest cell to MAX_CELL_VOLTAGE + CELL_VOLTAGE_DIFF_KEEP_MAX_VOLTAGE_UNTIL.
;      (for example 3.45V+0.01V =3.46V). If the voltage of the highest cell is above this level, CVL is reduced. If the voltage is below, CVL is
;      increased until cellcount*MAX_CELL_VOLTAGE.
;      An I-Part of 0.2 V/Vs (CVL_ICONTROLLER_FACTOR) has proved to be a stable and fast controlling-behaviour.
;      This method is not as fast as the penalty_sum-Method but usually smoother and more stable against toggeling and has no stationary deviation.
; More info: https://github.com/Louisvdw/dbus-serialbattery/pull/882
CVL_ICONTROLLER_MODE   = False
CVL_ICONTROLLER_FACTOR = 0.2


; --------- Temperature limitation (affecting CCL/DCL) ---------
; Description:
;     Maximal charge / discharge current will be in-/decreased depending on temperature
; Example:
;     The temperature limit will be monitored to control the currents. If there are two temperature senors,
;     then the worst case will be calculated and the more secure lower current will be set.
; Charge current control management referring to temperature enable (True/False).
CCCM_T_ENABLE = True
; Charge current control management referring to temperature enable (True/False).
DCCM_T_ENABLE = True

; Set steps to reduce battery current
; The current will be changed linear between those steps if LINEAR_LIMITATION_ENABLE is set to True
TEMPERATURES_WHILE_CHARGING      =    0,    2,    5,   10,   15,   20,   35,   40,   55
MAX_CHARGE_CURRENT_T_FRACTION    = 0.00, 0.10, 0.20, 0.40, 0.80, 1.00, 1.00, 0.40, 0.00

TEMPERATURES_WHILE_DISCHARGING   =  -20,    0,    5,   10,   15,   45,   55
MAX_DISCHARGE_CURRENT_T_FRACTION = 0.00, 0.20, 0.30, 0.40, 1.00, 1.00, 0.00


; --------- SOC limitation (affecting CCL/DCL) ---------
; Description:
;     Maximal charge / discharge current will be increased / decreased depending on State of Charge,
;     see CC_SOC_LIMIT1 etc.
; Example:
;     The SoC limit will be monitored to control the currents.
; Charge current control management enable (True/False).
CCCM_SOC_ENABLE = True
; Discharge current control management enable (True/False).
DCCM_SOC_ENABLE = True

; Set steps to reduce battery current
; The current will be changed linear between those steps if LINEAR_LIMITATION_ENABLE is set to True
SOC_WHILE_CHARGING                 =  100,   95,   90,   85
MAX_CHARGE_CURRENT_SOC_FRACTION    = 0.00, 0.15, 0.50, 1.00

SOC_WHILE_DISCHARGING              =    0,    5,   10,   15,   20
MAX_DISCHARGE_CURRENT_SOC_FRACTION = 0.00, 0.10, 0.20, 0.50, 1.00


; --------- Time-To-Go ---------
; Description:
;     Calculates the time to go shown in the GUI
;     Recalculation is done based on TIME_TO_SOC_RECALCULATE_EVERY
TIME_TO_GO_ENABLE = True


; --------- Time-To-Soc ---------
; Description:
;     Calculates the time to a specific SoC
; Example:
;     TIME_TO_SOC_POINTS = 50, 25, 15, 0
;     6h 24m remaining until 50% SoC
;     17h 36m remaining until 25% SoC
;     22h 5m remaining until 15% SoC
;     28h 48m remaining until 0% SoC
; Set of SoC percentages to report on dbus and MQTT. The more you specify the more it will impact system performance.
; [Valid values 0-100, comma separated list. More that 20 intervals are not recommended]
; Example: TIME_TO_SOC_POINTS = 100, 95, 90, 85, 75, 50, 25, 20, 10, 0
; Leave empty to disable
TIME_TO_SOC_POINTS =
; Specify TimeToSoc value type [Valid values 1, 2, 3]
; 1 Seconds
; 2 Time string <days>d <hours>h <minutes>m <seconds>s
; 3 Both seconds and time string "<seconds> [<days>d <hours>h <minutes>m <seconds>s]"
TIME_TO_SOC_VALUE_TYPE = 1
; Specify in seconds how often the TimeToSoc should be recalculated
; Minimum are 5 seconds to prevent CPU overload
TIME_TO_SOC_RECALCULATE_EVERY = 60
; Include TimeToSoC points when moving away from the SoC point [Valid values True, False]
; These will be as negative time. Disabling this improves performance slightly
TIME_TO_SOC_INC_FROM = False


; --------- Additional settings ---------
; Specify one or more BMS types to load else leave empty to try to load all available
; Available BMS:
;     Daly, Ecs, HeltecModbus, HLPdataBMS4S, Jkbms, Lifepower, LltJbd, Renogy, Seplos
; Available BMS, but disabled by default (just enter one or more below and it will be enabled):
;     ANT, MNB, Sinowealth
BMS_TYPE = Jkbms

; Exclute this serial devices from the driver startup
; Example:
;     /dev/ttyUSB2, /dev/ttyUSB4
EXCLUDED_DEVICES =

; Auto reset SoC
; If on, then SoC is reset to 100%, if the value switches from absorption to float voltage
; Currently only working for Daly BMS and JKBMS BLE
AUTO_RESET_SOC = True

; Publish the config settings to the dbus path "/Info/Config/"
PUBLISH_CONFIG_VALUES = True

; Select the format of cell data presented on dbus [Valid values 0,1,2,3]
; 0 Do not publish all the cells (only the min/max cell data as used by the default GX)
; 1 Format: /Voltages/Cell (also available for display on Remote Console)
; 2 Format: /Cell/#/Volts
; 3 Both formats 1 and 2
BATTERY_CELL_DATA_FORMAT = 1

; Simulate Midpoint graph (True/False).
MIDPOINT_ENABLE = False

; Battery temperature
; Specify how the battery temperature is assembled
; 0 Get mean of temperature sensor 1 to sensor 4
; 1 Get only temperature from temperature sensor 1
; 2 Get only temperature from temperature sensor 2
; 3 Get only temperature from temperature sensor 3
; 4 Get only temperature from temperature sensor 4
TEMP_BATTERY = 0

; Temperature sensor 1 name
TEMP_1_NAME = Temp 1

; Temperature sensor 2 name
TEMP_2_NAME = Temp 2

; Temperature sensor 2 name
TEMP_3_NAME = Temp 3

; Temperature sensor 2 name
TEMP_4_NAME = Temp 4


; --------- BMS specific settings ---------

; -- LltJbd settings
; SoC low levels
; Note:
;     SOC_LOW_WARNING is also used to calculate the Time-To-Go even if you are not using a LltJbd BMS
SOC_LOW_WARNING = 20
SOC_LOW_ALARM   = 10

; -- Daly settings
; Battery capacity (amps), if the BMS does not support reading it
BATTERY_CAPACITY = 50
; Invert Battery Current. Default non-inverted. Set to -1 to invert
INVERT_CURRENT_MEASUREMENT = 1

; -- ESC GreenMeter and Lipro device settings
GREENMETER_ADDRESS  = 1
LIPRO_START_ADDRESS = 2
LIPRO_END_ADDRESS   = 4
LIPRO_CELL_COUNT    = 15

; -- HeltecModbus (Heltec SmartBMS/YYBMS) settings
; Set the Modbus addresses from the adapters
; Separate each address to check by a comma like: 1, 2, 3, ...
; factory default address will be 1
HELTEC_MODBUS_ADDR = 1


; --------- Voltage drop ---------
; If you have a voltage drop between the BMS and the charger because of wire size or length
; then you can specify the voltage drop here. The driver will then add the voltage drop
; to the calculated CVL to compensate.
; Example:
;     cell count: 16
;     MAX_CELL_VOLTAGE = 3.45
;     max voltage calculated = 16 * 3.45 = 55.20
;     CVL is set to 55.20 V and the battery is now charged until the charger reaches 55.20 V.
;     The BMS now measures 55.05 V since there is a voltage drop of 0.15 V on the cable.
;     Since the dbus-serialbattery reads the voltage of 55.05 V from the BMS the max voltage
;     of 55.20 V is never reached and max voltage is kept forever.
;     By setting the VOLTAGE_DROP to 0.15 V the voltage on the charger is increased and the
;     target voltage on the BMS is reached.
VOLTAGE_DROP = 0.00
```

### Relevant log output

```shell
root@raspberrypi2:/data/etc/dbus-serialbattery# tail -F -n 100 /data/log/dbus-blebattery.0/current | tai64nlocal
2024-02-26 19:02:23.567869500 Device C8:47:8C:ED:06:11 (public)
2024-02-26 19:02:23.567875500   Alias: JKBMS-Heating
2024-02-26 19:02:23.567878500   Paired: no
2024-02-26 19:02:23.567879500   Trusted: no
2024-02-26 19:02:23.567881500   Blocked: no
2024-02-26 19:02:23.567883500   Connected: no
2024-02-26 19:02:23.567885500   LegacyPairing: no
2024-02-26 19:02:23.567887500   UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
2024-02-26 19:02:23.567891500   RSSI: -67
2024-02-26 19:02:23.569241500 
2024-02-26 19:02:24.787225500 INFO:SerialBattery:
2024-02-26 19:02:24.787877500 INFO:SerialBattery:Starting dbus-serialbattery
2024-02-26 19:02:24.789554500 INFO:SerialBattery:Venus OS v3.20
2024-02-26 19:02:24.790209500 INFO:SerialBattery:dbus-serialbattery v1.2.20240219beta
2024-02-26 19:02:40.824914500 Traceback (most recent call last):
2024-02-26 19:02:40.824921500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 247, in <module>
2024-02-26 19:02:40.824926500     main()
2024-02-26 19:02:40.824928500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 178, in main
2024-02-26 19:02:40.824933500     from bms.jkbms_ble import Jkbms_Ble  # noqa: F401
2024-02-26 19:02:40.824936500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_ble.py", line 7, in <module>
2024-02-26 19:02:40.825070500     from bms.jkbms_brn import Jkbms_Brn
2024-02-26 19:02:40.825073500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_brn.py", line 2, in <module>
2024-02-26 19:02:40.825078500     from bleak import BleakScanner, BleakClient
2024-02-26 19:02:40.825081500 ModuleNotFoundError: No module named 'bleak'
2024-02-26 19:02:41.028727500 
2024-02-26 19:02:41.028854500 INFO:Bluetooth details
2024-02-26 19:02:41.066485500 [CHG] Device C8:47:8C:ED:06:11 RSSI: -67
2024-02-26 19:02:41.234045500 Attempting to disconnect from C8:47:8C:ED:06:11
2024-02-26 19:02:41.234053500 [CHG] Device D5:F3:6C:03:B5:1A RSSI is nil
2024-02-26 19:02:41.234057500 [CHG] Device F4:4A:37:E1:C9:5E RSSI is nil
2024-02-26 19:02:41.234060500 [CHG] Device E4:D7:D6:1D:1F:32 RSSI is nil
2024-02-26 19:02:41.234064500 [CHG] Device F4:15:5A:64:5A:33 RSSI is nil
2024-02-26 19:02:41.234068500 [CHG] Device 77:12:3F:D2:02:36 RSSI is nil
2024-02-26 19:02:41.234072500 [CHG] Device F3:4A:2D:BA:30:26 RSSI is nil
2024-02-26 19:02:41.234174500 [CHG] Device C5:16:51:8B:7F:F0 RSSI is nil
2024-02-26 19:02:41.234178500 [CHG] Device C6:4C:BF:44:C7:70 RSSI is nil
2024-02-26 19:02:41.234182500 [CHG] Device 5A:61:28:92:55:A3 TxPower is nil
2024-02-26 19:02:41.234186500 [CHG] Device 5A:61:28:92:55:A3 RSSI is nil
2024-02-26 19:02:41.234190500 [CHG] Device CE:75:EC:BD:43:74 RSSI is nil
2024-02-26 19:02:41.234193500 [CHG] Device 75:8C:CC:98:72:28 TxPower is nil
2024-02-26 19:02:41.234220500 [CHG] Device 75:8C:CC:98:72:28 RSSI is nil
2024-02-26 19:02:41.234224500 [CHG] Device CD:F3:59:F5:20:C7 RSSI is nil
2024-02-26 19:02:41.234227500 [CHG] Device A0:FB:C5:B4:E8:DF TxPower is nil
2024-02-26 19:02:41.234231500 [CHG] Device A0:FB:C5:B4:E8:DF RSSI is nil
2024-02-26 19:02:41.234235500 [CHG] Device C8:47:8C:ED:06:11 RSSI is nil
2024-02-26 19:02:41.234288500 [CHG] Device 68:24:17:D1:62:AE TxPower is nil
2024-02-26 19:02:41.234292500 [CHG] Device 68:24:17:D1:62:AE RSSI is nil
2024-02-26 19:02:41.234296500 [CHG] Device 51:8F:7B:25:A9:D7 TxPower is nil
2024-02-26 19:02:41.234300500 [CHG] Device 51:8F:7B:25:A9:D7 RSSI is nil
2024-02-26 19:02:41.234303500 [CHG] Device 79:69:39:C6:B2:EA RSSI is nil
2024-02-26 19:02:41.234307500 [CHG] Device 5D:E8:00:F7:C3:88 RSSI is nil
2024-02-26 19:02:41.234333500 [CHG] Device 6C:37:97:0B:E7:A0 RSSI is nil
2024-02-26 19:02:41.234337500 [CHG] Device 80:64:6F:D0:D4:86 RSSI is nil
2024-02-26 19:02:41.234341500 [CHG] Device CF:2A:70:C2:D2:AD RSSI is nil
2024-02-26 19:02:41.234344500 [CHG] Controller B8:27:EB:56:EA:F6 Discovering: no
2024-02-26 19:02:41.234348500 Successful disconnected
2024-02-26 19:02:46.353904500 Device C8:47:8C:ED:06:11 (public)
2024-02-26 19:02:46.353912500   Alias: JKBMS-Heating
2024-02-26 19:02:46.353914500   Paired: no
2024-02-26 19:02:46.353916500   Trusted: no
2024-02-26 19:02:46.353918500   Blocked: no
2024-02-26 19:02:46.353920500   Connected: no
2024-02-26 19:02:46.353921500   LegacyPairing: no
2024-02-26 19:02:46.353923500   UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
2024-02-26 19:02:46.353928500   RSSI: -67
2024-02-26 19:02:46.355104500 
2024-02-26 19:02:47.505842500 INFO:SerialBattery:
2024-02-26 19:02:47.506262500 INFO:SerialBattery:Starting dbus-serialbattery
2024-02-26 19:02:47.507646500 INFO:SerialBattery:Venus OS v3.20
2024-02-26 19:02:47.508057500 INFO:SerialBattery:dbus-serialbattery v1.2.20240219beta
2024-02-26 19:03:03.531442500 Traceback (most recent call last):
2024-02-26 19:03:03.531450500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 247, in <module>
2024-02-26 19:03:03.531455500     main()
2024-02-26 19:03:03.531457500   File "/opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py", line 178, in main
2024-02-26 19:03:03.531462500     from bms.jkbms_ble import Jkbms_Ble  # noqa: F401
2024-02-26 19:03:03.531465500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_ble.py", line 7, in <module>
2024-02-26 19:03:03.531595500     from bms.jkbms_brn import Jkbms_Brn
2024-02-26 19:03:03.531599500   File "/opt/victronenergy/dbus-serialbattery/bms/jkbms_brn.py", line 2, in <module>
2024-02-26 19:03:03.531603500     from bleak import BleakScanner, BleakClient
2024-02-26 19:03:03.531607500 ModuleNotFoundError: No module named 'bleak'
2024-02-26 19:03:03.738832500 
2024-02-26 19:03:03.738969500 INFO:Bluetooth details
2024-02-26 19:03:03.743020500 [CHG] Device C8:47:8C:ED:06:11 RSSI: -67
2024-02-26 19:03:03.859798500 Attempting to disconnect from C8:47:8C:ED:06:11
2024-02-26 19:03:03.859804500 Successful disconnected
2024-02-26 19:03:08.976151500 Device C8:47:8C:ED:06:11 (public)
2024-02-26 19:03:08.976157500   Alias: JKBMS-Heating
2024-02-26 19:03:08.976159500   Paired: no
2024-02-26 19:03:08.976161500   Trusted: no
2024-02-26 19:03:08.976162500   Blocked: no
2024-02-26 19:03:08.976164500   Connected: no
2024-02-26 19:03:08.976166500   LegacyPairing: no
2024-02-26 19:03:08.976168500   UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
2024-02-26 19:03:08.976172500   RSSI: -72
2024-02-26 19:03:08.979526500 
2024-02-26 19:03:10.209123500 INFO:SerialBattery:
2024-02-26 19:03:10.209664500 INFO:SerialBattery:Starting dbus-serialbattery
2024-02-26 19:03:10.211289500 INFO:SerialBattery:Venus OS v3.20
2024-02-26 19:03:10.211752500 INFO:SerialBattery:dbus-serialbattery v1.2.20240219beta
```

### Any other information that may be helpful

The second battery is not seen bay the scan it should find Jkbms_Ble C8:47:8C:EE:29:AF

iscovery started
[CHG] Device C8:47:8C:ED:06:11 RSSI: -66
[CHG] Device 45:38:38:75:90:3E RSSI: -75
[CHG] Device 5D:E8:00:F7:C3:88 RSSI: -64
[CHG] Device F4:15:5A:64:5A:33 RSSI: -71
[CHG] Device CE:75:EC:BD:43:74 ManufacturerData Key: 0x0499
[CHG] Device CE:75:EC:BD:43:74 ManufacturerData Value:
  05 10 35 44 6e bd 60 00 08 00 10 03 f8 b1 16 b3  ..5Dn.`.........
  f9 2b ce 75 ec bd 43 74                          .+.u..Ct        
[CHG] Device 68:24:17:D1:62:AE RSSI: -57
[CHG] Device F3:4A:2D:BA:30:26 RSSI: -70
[CHG] Device F3:4A:2D:BA:30:26 ManufacturerData Key: 0x0499
[CHG] Device F3:4A:2D:BA:30:26 ManufacturerData Value:
  05 f3 36 3f 44 bd 4d fc 50 01 c8 00 18 7d 56 5c  ..6?D.M.P....}V\
  40 8b f3 4a 2d ba 30 26                          @..J-.0&        
[CHG] Device C5:16:51:8B:7F:F0 RSSI: -70
[CHG] Device F4:4A:37:E1:C9:5E RSSI: -80
root@raspberrypi2:/data/etc/dbus-serialbattery# bluetoothctl scan on
Discovery started
[CHG] Device 5D:E8:00:F7:C3:88 RSSI: -72
[CHG] Device 79:69:39:C6:B2:EA RSSI: -96
[CHG] Device 79:69:39:C6:B2:EA ManufacturerData Key: 0x004c
[CHG] Device 79:69:39:C6:B2:EA ManufacturerData Value:
  0c 0e 00 8d 14 b9 5f d5 36 f7 d9 47 37 52 38 1d  ......_.6..G7R8.
  10 06 0b 1d 01 5f 28 38                          ....._(8        
[CHG] Device A0:FB:C5:B4:E8:DF RSSI: -55
[CHG] Device 6C:37:97:0B:E7:A0 ManufacturerData Key: 0x004c
[CHG] Device 6C:37:97:0B:E7:A0 ManufacturerData Value:
  0c 0e 00 8d 14 b9 5f d5 36 f7 d9 47 37 52 38 1d  ......_.6..G7R8.
  10 06 0b 1d 01 5f 28 38                          ....._(8        
[CHG] Device D5:F3:6C:03:B5:1A RSSI: -53
[CHG] Device D5:F3:6C:03:B5:1A ManufacturerData Key: 0x02e1
[CHG] Device D5:F3:6C:03:B5:1A ManufacturerData Value:
  10 02 89 a3 02 b5 18 aa ad a6 e6 d4 cb 6e dd 7b  .............n.{
  79 45 c8 28 3b 43 9e                             yE.(;C.         
[CHG] Device 51:8F:7B:25:A9:D7 RSSI: -52
[CHG] Device CE:75:EC:BD:43:74 ManufacturerData Key: 0x0499
[CHG] Device CE:75:EC:BD:43:74 ManufacturerData Value:
  05 10 31 44 40 bd 6a 00 0c 00 10 03 f8 b1 96 b3  ..1D@.j.........
  f9 34 ce 75 ec bd 43 74                          .4.u..Ct        
[CHG] Device 5A:61:28:92:55:A3 RSSI: -88
[CHG] Device F3:4A:2D:BA:30:26 RSSI: -89
[CHG] Device F3:4A:2D:BA:30:26 ManufacturerData Key: 0x0499
[CHG] Device F3:4A:2D:BA:30:26 ManufacturerData Value:
  05 f3 2f 3f 43 bd 53 fc 58 01 c4 00 14 7d 56 5c  ../?C.S.X....}V\
  40 94 f3 4a 2d ba 30 26                          @..J-.0&        
[CHG] Device CD:F3:59:F5:20:C7 RSSI: -71
[CHG] Device 77:12:3F:D2:02:36 RSSI: -68
[CHG] Device F4:15:5A:64:5A:33 RSSI: -71
[CHG] Device E4:D7:D6:1D:1F:32 RSSI: -

**Comment by mr-manuel** [comment]
Did youbuse the search first?

See https://github.com/Louisvdw/dbus-serialbattery/issues?q=module+named+bleak

**Comment by githubfrance** [comment]
HI 
The bleak module can not be installed because de pip cant be installed

/data/etc/dbus-serialbattery# opkg install python3-misc python3-pip

Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - nothing provides requested libsysfs2
 * 
 * Solution 1:
 *   - do not ask to install a package providing libsysfs2


The solution was to force the update Venus OS
opt/victronenergy/swupdate-scripts/set-feed.sh release
/opt/victronenergy/swupdate-scripts/check-updates.sh -update -force
